### ISSUE TITLE
A torrent file with a piece length of zero crashes the CLI app

### ISSUE THREAD

**Issue by notriddle** [anacrolix/torrent#112]
## A test case

```
d13:announce-listll35:udp://tracker.openbittorrent.com:80el29:udp://tracker.publicbt.com:80el28:udp://tracker.istole.it:6969ee7:comment7:yoloham10:created by28:github.com/anacrolix/torrent13:creation datei1473643191e4:infod4:name5:empty12:piece lengthi0e6:piecesleee
```

## What I expected

It should either produce an actual error message calling this torrent file malformed, or it should just not download anything (if the pieces have zero length, then all the files must be empty).

## What actually happened

```
panic: runtime error: integer divide by zero
[signal 0x8 code=0x1 addr=0x555fbb pc=0x555fbb]

goroutine 1 [running]:
github.com/anacrolix/torrent.validateInfo(0xc820020ba0, 0x0, 0x0)
	/home/michael/LABdivus/quicktrip/src/github.com/anacrolix/torrent/misc.go:65 +0x17b
github.com/anacrolix/torrent.(*Torrent).setInfoBytes(0xc820156000, 0xc8200fbda0, 0x2b, 0x30, 0x0, 0x0)
	/home/michael/LABdivus/quicktrip/src/github.com/anacrolix/torrent/torrent.go:252 +0x3ee
github.com/anacrolix/torrent.(*Torrent).SetInfoBytes(0xc820156000, 0xc8200fbda0, 0x2b, 0x30, 0x0, 0x0)
	/home/michael/LABdivus/quicktrip/src/github.com/anacrolix/torrent/torrent.go:1125 +0xbe
github.com/anacrolix/torrent.(*Client).AddTorrentSpec(0xc8200ef180, 0xc820130bd0, 0xc820156000, 0xc820034101, 0x0, 0x0)
	/home/michael/LABdivus/quicktrip/src/github.com/anacrolix/torrent/client.go:1480 +0xff
github.com/anacrolix/torrent.(*Client).AddTorrent(0xc8200ef180, 0xc82013c140, 0xc82013c140, 0x0, 0x0)
	/home/michael/LABdivus/quicktrip/src/github.com/anacrolix/torrent/client.go:1763 +0x4b
main.addTorrents.func1(0xc820107df0, 0xc8200ef180, 0x0)
	/home/michael/LABdivus/quicktrip/src/github.com/anacrolix/torrent/cmd/torrent/main.go:84 +0x42b
main.addTorrents(0xc8200ef180)
	/home/michael/LABdivus/quicktrip/src/github.com/anacrolix/torrent/cmd/torrent/main.go:71 +0xab
main.main()
	/home/michael/LABdivus/quicktrip/src/github.com/anacrolix/torrent/cmd/torrent/main.go:143 +0x347

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1721 +0x1

goroutine 6 [runnable]:
sync.runtime_Semacquire(0xf156d4)
	/usr/lib/golang/src/runtime/sema.go:43 +0x26
sync.(*Mutex).Lock(0xf156d0)
	/usr/lib/golang/src/sync/mutex.go:82 +0x1c4
sync.(*RWMutex).Lock(0xf156d0)
	/usr/lib/golang/src/sync/rwmutex.go:82 +0x30
github.com/anacrolix/sync.(*RWMutex).Lock(0xf155a0)
	/home/michael/LABdivus/quicktrip/src/github.com/anacrolix/sync/rwmutex.go:18 +0x57
github.com/anacrolix/utp.(*Socket).reader(0xc8200eab60)
	/home/michael/LABdivus/quicktrip/src/github.com/anacrolix/utp/socket.go:150 +0x1cd
created by github.com/anacrolix/utp.NewSocketFromPacketConn
	/home/michael/LABdivus/quicktrip/src/github.com/anacrolix/utp/socket.go:85 +0x186

goroutine 7 [runnable]:
sync.runtime_Syncsemacquire(0xc8200ef458)
	/usr/lib/golang/src/runtime/sema.go:237 +0x201
sync.(*Cond).Wait(0xc8200ef448)
	/usr/lib/golang/src/sync/cond.go:62 +0x9b
github.com/anacrolix/torrent.(*Client).waitAccept(0xc8200ef180)
	/home/michael/LABdivus/quicktrip/src/github.com/anacrolix/torrent/client.go:378 +0xe9
github.com/anacrolix/torrent.(*Client).acceptConnections(0xc8200ef180, 0x7f0c1d9f0da8, 0xc820034170, 0x7f0c1d9f0d00)
	/home/michael/LABdivus/quicktrip/src/github.com/anacrolix/torrent/client.go:386 +0x97
created by github.com/anacrolix/torrent.NewClient
	/home/michael/LABdivus/quicktrip/src/github.com/anacrolix/torrent/client.go:295 +0x7b6

goroutine 8 [runnable]:
github.com/anacrolix/torrent.(*Client).acceptConnections(0xc8200ef180, 0x7f0c1d9f1eb8, 0xc8200eab60, 0x7f0c1d9f0d01)
	/home/michael/LABdivus/quicktrip/src/github.com/anacrolix/torrent/client.go:382
created by github.com/anacrolix/torrent.NewClient
	/home/michael/LABdivus/quicktrip/src/github.com/anacrolix/torrent/client.go:298 +0x82b

goroutine 9 [runnable]:
github.com/anacrolix/torrent/dht.NewServer.func1(0xc820034180)
	/home/michael/LABdivus/quicktrip/src/github.com/anacrolix/torrent/dht/server.go:102
created by github.com/anacrolix/torrent/dht.NewServer
	/home/michael/LABdivus/quicktrip/src/github.com/anacrolix/torrent/dht/server.go:112 +0x3aa

goroutine 10 [runnable]:
github.com/anacrolix/torrent/dht.(*Server).addRootNodes(0xc8200fd560, 0xb2f6b0, 0xc8200fd598)
	/home/michael/LABdivus/quicktrip/src/github.com/anacrolix/torrent/dht/server.go:541
github.com/anacrolix/torrent/dht.(*Server).bootstrap(0xc8200fd560, 0x0, 0x0)
	/home/michael/LABdivus/quicktrip/src/github.com/anacrolix/torrent/dht/server.go:569 +0xe0
github.com/anacrolix/torrent/dht.NewServer.func2(0xc820034180)
	/home/michael/LABdivus/quicktrip/src/github.com/anacrolix/torrent/dht/server.go:114 +0x34
created by github.com/anacrolix/torrent/dht.NewServer
	/home/michael/LABdivus/quicktrip/src/github.com/anacrolix/torrent/dht/server.go:122 +0x3cc

goroutine 11 [runnable]:
github.com/gosuri/uiprogress.(*Progress).Listen(0xc820014690)
	/home/michael/LABdivus/quicktrip/src/github.com/gosuri/uiprogress/progress.go:87
created by github.com/gosuri/uiprogress.(*Progress).Start
	/home/michael/LABdivus/quicktrip/src/github.com/gosuri/uiprogress/progress.go:110 +0x7f
```

**Comment by anacrolix** [comment]
Thanks for the reports!

**Comment by anacrolix** [comment]
This should be fixed if you'd like to verify.

**Comment by notriddle** [comment]
It works. Thanks!
