### ISSUE TITLE
torrent-verify CLI explodes with a SIGBUS on a truncated torrent

### ISSUE THREAD

**Issue by BonkaBonka** [anacrolix/torrent#141]
I'm using the latest packaged Go on Arch Linux:
~~~
$ go version
go version go1.7.4 linux/amd64
~~~

I'm building `torrent-verify` like this:
~~~
$ mkdir -p ~/build/torrent && cd ~/build/torrent
$ GOPATH=$PWD go get github.com/anacrolix/torrent/cmd/torrent-verify
$ cp bin/torrent-verify ~/bin
~~~

Because I had a SMART error, I'm verifying downloads:
~~~
$ cd ~/downloads/distros
$ torrent-verify -torrent CentOS-7-x86_64-NetInstall-1611.torrent -path ./
2016/12/29 19:03:56 main.go:63: 6
2016/12/29 19:03:56 main.go:68: 395319474
2016/12/29 19:03:56 main.go:69: 15100
0: cf12d532d66f50aaebf3aa337113dc505a0eab00: true
... snip ...
754: 774bdf649b9c80e735699b388ec69b1d90755b68: true
~~~

So far, so good.  But if I simulate a truncated file:
~~~
$ echo > CentOS-7-x86_64-NetInstall-1611/CentOS-7-x86_64-NetInstall-1611.iso 
$ torrent-verify -torrent CentOS-7-x86_64-NetInstall-1611.torrent -path ./
2016/12/29 19:07:17 main.go:63: 6
2016/12/29 19:07:17 main.go:68: 395319474
2016/12/29 19:07:17 main.go:69: 15100
unexpected fault address 0x7f243d12c000
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7f243d12c000 pc=0x45abae]

goroutine 1 [running]:
runtime.throw(0x67a510, 0x5)
	/usr/lib/go/src/runtime/panic.go:566 +0x95 fp=0xc4200478f8 sp=0xc4200478d8
runtime.sigpanic()
	/usr/lib/go/src/runtime/sigpanic_unix.go:21 +0xf3 fp=0xc420047950 sp=0xc4200478f8
runtime.memmove(0xc4201029c2, 0x7f243d12b000, 0x763e)
	/usr/lib/go/src/runtime/memmove_amd64.s:100 +0xae fp=0xc420047958 sp=0xc420047950
github.com/anacrolix/torrent/mmap_span.MMapSpan.ReadAt.func1(0x0, 0x77bb60, 0xc4200bdbe0, 0x0)
	/home/bonka/build/torrent/src/github.com/anacrolix/torrent/mmap_span/mmap_span.go:45 +0xc8 fp=0xc4200479a8 sp=0xc420047958
github.com/anacrolix/torrent/mmap_span.span.ApplyTo(0xc420078380, 0x6, 0x8, 0x0, 0xc420047a20)
	/home/bonka/build/torrent/src/github.com/anacrolix/torrent/mmap_span/span.go:15 +0xb4 fp=0xc4200479f8 sp=0xc4200479a8
github.com/anacrolix/torrent/mmap_span.MMapSpan.ReadAt(0xc420078380, 0x6, 0x8, 0xc4201029c2, 0x763e, 0x763e, 0x0, 0x9c2, 0x6, 0xc420047ae8)
	/home/bonka/build/torrent/src/github.com/anacrolix/torrent/mmap_span/mmap_span.go:49 +0x89 fp=0xc420047a48 sp=0xc4200479f8
github.com/anacrolix/torrent/mmap_span.(*MMapSpan).ReadAt(0xc4200bdb60, 0xc420102000, 0x8000, 0x8000, 0x0, 0x64c7a0, 0x7f2456964201, 0x0)
	<autogenerated>:18 +0x8f fp=0xc420047aa8 sp=0xc420047a48
io.(*SectionReader).Read(0xc420017530, 0xc420102000, 0x8000, 0x8000, 0x8000, 0x8000, 0x7b7420)
	/usr/lib/go/src/io/io.go:463 +0x7c fp=0xc420047af8 sp=0xc420047aa8
io.copyBuffer(0x7f2456964290, 0xc420052690, 0x77aba0, 0xc420017530, 0xc420102000, 0x8000, 0x8000, 0x64c7a0, 0xc420047e00, 0x7f2456964290)
	/usr/lib/go/src/io/io.go:390 +0x147 fp=0xc420047b80 sp=0xc420047af8
io.Copy(0x7f2456964290, 0xc420052690, 0x77aba0, 0xc420017530, 0xc420052690, 0x2f3, 0x2)
	/usr/lib/go/src/io/io.go:360 +0x68 fp=0xc420047be0 sp=0xc420047b80
main.main()
	/home/bonka/build/torrent/src/github.com/anacrolix/torrent/cmd/torrent-verify/main.go:73 +0x762 fp=0xc420047f48 sp=0xc420047be0
runtime.main()
	/usr/lib/go/src/runtime/proc.go:183 +0x1f4 fp=0xc420047fa0 sp=0xc420047f48
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420047fa8 sp=0xc420047fa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2086 +0x1
~~~

**Comment by BonkaBonka** [comment]
Perhaps related to this is if your torrent is long, that is to say it has extra garbage appended to it, torrent-verify doesn't complain about that either.
