### ISSUE TITLE
[bencode] panic: interface conversion: interface {} is string, not int64 [recovered]

### ISSUE THREAD

**Issue by mh-cbon** [anacrolix/torrent#166]
Hi,

Can we fix bencoder to not panic when a runtime error is met ?

I d prefer it simply return error (https://github.com/anacrolix/torrent/blob/master/bencode/decode.go#L29), like it tries to do at https://github.com/anacrolix/dht/blob/master/server.go#L167

```
panic: interface conversion: interface {} is string, not int64 [recovered]
	panic: interface conversion: interface {} is string, not int64

goroutine 7 [running]:
github.com/anacrolix/torrent/bencode.(*Decoder).Decode.func1(0xc420055d28)
	/home/mh-cbon/gow/src/github.com/anacrolix/torrent/bencode/decode.go:29 +0xea
panic(0x81d5a0, 0xc4204b7b00)
	/home/mh-cbon/.gvm/gos/go1.8/src/runtime/panic.go:489 +0x2cf
github.com/anacrolix/dht/krpc.(*Error).UnmarshalBencode(0xc420485760, 0xc4204a2a00, 0x20, 0x280, 0xc420485760, 0x16)
	/home/mh-cbon/gow/src/github.com/anacrolix/dht/krpc/error.go:34 +0x1b8
github.com/anacrolix/torrent/bencode.(*Decoder).parseUnmarshaler(0xc4204a4360, 0x8488e0, 0xc420485760, 0x199, 0xc420485760)
	/home/mh-cbon/gow/src/github.com/anacrolix/torrent/bencode/decode.go:397 +0x1aa
github.com/anacrolix/torrent/bencode.(*Decoder).parseValue(0xc4204a4360, 0x825380, 0xc420457a10, 0x196, 0x1)
	/home/mh-cbon/gow/src/github.com/anacrolix/torrent/bencode/decode.go:423 +0x6d
github.com/anacrolix/torrent/bencode.(*Decoder).parseDict(0xc4204a4360, 0x872a60, 0xc4204579d0, 0x199)
	/home/mh-cbon/gow/src/github.com/anacrolix/torrent/bencode/decode.go:277 +0x19c
github.com/anacrolix/torrent/bencode.(*Decoder).parseValue(0xc4204a4360, 0x872a60, 0xc4204579d0, 0x199, 0xc4204579d0)
	/home/mh-cbon/gow/src/github.com/anacrolix/torrent/bencode/decode.go:444 +0x21c
github.com/anacrolix/torrent/bencode.(*Decoder).Decode(0xc4204a4360, 0x825400, 0xc4204579d0, 0x0, 0x0)
	/home/mh-cbon/gow/src/github.com/anacrolix/torrent/bencode/decode.go:40 +0x1f3
github.com/anacrolix/torrent/bencode.Unmarshal(0xc42016a000, 0x3b, 0x10000, 0x825400, 0xc4204579d0, 0xc42048fd62, 0xd)
	/home/mh-cbon/gow/src/github.com/anacrolix/torrent/bencode/api.go:128 +0x113
github.com/anacrolix/dht.(*Server).processPacket(0xc420128000, 0xc42016a000, 0x3b, 0x10000, 0xa79220, 0xc4204b7ac0)
	/home/mh-cbon/gow/src/github.com/anacrolix/dht/server.go:169 +0xf1
github.com/anacrolix/dht.(*Server).serve(0xc420128000, 0x0, 0x0)
	/home/mh-cbon/gow/src/github.com/anacrolix/dht/server.go:238 +0x24f
github.com/anacrolix/dht.NewServer.func1(0xc42000e158)
	/home/mh-cbon/gow/src/github.com/anacrolix/dht/server.go:114 +0x32
created by github.com/anacrolix/dht.NewServer
	/home/mh-cbon/gow/src/github.com/anacrolix/dht/server.go:123 +0x2db
exit status 2
```

**Comment by anacrolix** [comment]
The true error here is at github.com/anacrolix/dht/krpc/error.go:34, which shouldn't be assuming the correct type in the packet. I'll push a fix in a sec.
