### ISSUE TITLE
torrentfs gets stuck on OSX Sierra

### ISSUE THREAD

**Issue by themihai** [anacrolix/torrent#180]
I'm trying to run torrentFS on OSX sierra but it gets stuck whenever I try to read any file directory/files are displayed but can't read the files regardless of how small <i.e. cat tex files > or large < video> they are.  Is this a known issue? Is quite hard to figure out what's wrong because I can't get any error/debug info except the dirwatch event ( ``dirwatch.go:52: event: "torrents/sometorrent.torrent": CREATE ``)

**Comment by themihai** [comment]
After a while (waiting to get the contents of a directory) I've got this panic

```
2017/08/20 20:20:57 serve.go:859: fuse: panic in handler for Read [ID=0xf Node=0x4 Uid=501 Gid=20 Pid=380] 0x2 838 @0x0 dir=true fl=0 lock=0 ffl=OpenReadOnly: runtime error: index out of range
goroutine 2127 [running]:
bazil.org/fuse/fs.(*Server).serve.func2(0x4938ba0, 0xc4273ee070, 0xc42526bef8, 0xc42526be57)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:857 +0x1b1
panic(0x4627fc0, 0x495f400)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/panic.go:489 +0x2cf
github.com/anacrolix/torrent/fs.dirNode.ReadDirAll(0xc420019068, 0x6, 0xc42011c0e0, 0xc420070600, 0xc420136c80, 0x4fa1040, 0xc4273c2500, 0x4010203, 0x462dce0, 0x465d4c0, ...)
	/Users/themihai/go/src/github.com/anacrolix/torrent/fs/torrentfs.go:180 +0x367
github.com/anacrolix/torrent/fs.(*dirNode).ReadDirAll(0xc427204960, 0x4fa1040, 0xc4273c2500, 0x6140c28, 0xc427204960, 0x301, 0x0, 0x4933f60)
	<autogenerated>:5 +0x84
bazil.org/fuse/fs.(*Server).handleRequest(0xc4200f00c0, 0x4fa1040, 0xc4273c2500, 0x4934760, 0xc427204960, 0xc4271e7d40, 0x4938ba0, 0xc4273ee070, 0xc42526bef8, 0x0, ...)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:1209 +0x45a
bazil.org/fuse/fs.(*Server).serve(0xc4200f00c0, 0x4938ba0, 0xc4273ee070)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:878 +0x495
bazil.org/fuse/fs.(*Server).Serve.func1(0xc4200f00c0, 0x4938ba0, 0xc4273ee070)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:425 +0x6e
created by bazil.org/fuse/fs.(*Server).Serve
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:426 +0x3c4
2017/08/20 20:20:57 serve.go:859: fuse: panic in handler for Read [ID=0x11 Node=0x4 Uid=501 Gid=20 Pid=380] 0x2 1676 @0x0 dir=true fl=0 lock=0 ffl=OpenReadOnly: runtime error: index out of range
goroutine 2128 [running]:
bazil.org/fuse/fs.(*Server).serve.func2(0x4938ba0, 0xc4273ee150, 0xc42526bef8, 0xc42526be57)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:857 +0x1b1
panic(0x4627fc0, 0x495f400)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/panic.go:489 +0x2cf
github.com/anacrolix/torrent/fs.dirNode.ReadDirAll(0xc420019068, 0x6, 0xc42011c0e0, 0xc420070600, 0xc420136c80, 0x4fa1040, 0xc4273c2780, 0x4010203, 0x462dce0, 0x465d4c0, ...)
	/Users/themihai/go/src/github.com/anacrolix/torrent/fs/torrentfs.go:180 +0x367
github.com/anacrolix/torrent/fs.(*dirNode).ReadDirAll(0xc427204960, 0x4fa1040, 0xc4273c2780, 0x6140c28, 0xc427204960, 0x601, 0x0, 0x4933f60)
	<autogenerated>:5 +0x84
bazil.org/fuse/fs.(*Server).handleRequest(0xc4200f00c0, 0x4fa1040, 0xc4273c2780, 0x4934760, 0xc427204960, 0xc4271e7d40, 0x4938ba0, 0xc4273ee150, 0xc42526bef8, 0x0, ...)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:1209 +0x45a
bazil.org/fuse/fs.(*Server).serve(0xc4200f00c0, 0x4938ba0, 0xc4273ee150)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:878 +0x495
bazil.org/fuse/fs.(*Server).Serve.func1(0xc4200f00c0, 0x4938ba0, 0xc4273ee150)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:425 +0x6e
created by bazil.org/fuse/fs.(*Server).Serve
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:426 +0x3c4
2017/08/20 20:20:57 serve.go:859: fuse: panic in handler for Read [ID=0xa Node=0x4 Uid=501 Gid=20 Pid=380] 0x2 3353 @0x0 dir=true fl=0 lock=0 ffl=OpenReadOnly: runtime error: index out of range
goroutine 2129 [running]:
bazil.org/fuse/fs.(*Server).serve.func2(0x4938ba0, 0xc4273ee230, 0xc42526bef8, 0xc42526be57)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:857 +0x1b1
panic(0x4627fc0, 0x495f400)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/panic.go:489 +0x2cf
github.com/anacrolix/torrent/fs.dirNode.ReadDirAll(0xc420019068, 0x6, 0xc42011c0e0, 0xc420070600, 0xc420136c80, 0x4fa1040, 0xc4273c2840, 0x4010203, 0x462dce0, 0x465d4c0, ...)
	/Users/themihai/go/src/github.com/anacrolix/torrent/fs/torrentfs.go:180 +0x367
github.com/anacrolix/torrent/fs.(*dirNode).ReadDirAll(0xc427204960, 0x4fa1040, 0xc4273c2840, 0x6140c28, 0xc427204960, 0xd01, 0x0, 0x4933f60)
	<autogenerated>:5 +0x84
bazil.org/fuse/fs.(*Server).handleRequest(0xc4200f00c0, 0x4fa1040, 0xc4273c2840, 0x4934760, 0xc427204960, 0xc4271e7d40, 0x4938ba0, 0xc4273ee230, 0xc42526bef8, 0x0, ...)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:1209 +0x45a
bazil.org/fuse/fs.(*Server).serve(0xc4200f00c0, 0x4938ba0, 0xc4273ee230)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:878 +0x495
bazil.org/fuse/fs.(*Server).Serve.func1(0xc4200f00c0, 0x4938ba0, 0xc4273ee230)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:425 +0x6e
created by bazil.org/fuse/fs.(*Server).Serve
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:426 +0x3c4
2017/08/20 20:20:57 serve.go:859: fuse: panic in handler for Lookup [ID=0x7 Node=0x4 Uid=501 Gid=20 Pid=380] ".DS_Store": runtime error: index out of range
goroutine 2151 [running]:
bazil.org/fuse/fs.(*Server).serve.func2(0x4938aa0, 0xc4273f48c0, 0xc42526bef8, 0xc42526be57)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:857 +0x1b1
panic(0x4627fc0, 0x495f400)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/panic.go:489 +0x2cf
github.com/anacrolix/torrent/fs.dirNode.Lookup(0xc420019068, 0x6, 0xc42011c0e0, 0xc420070600, 0xc420136c80, 0x4fa1040, 0xc4273c3140, 0xc4273b0013, 0x9, 0x462e860, ...)
	/Users/themihai/go/src/github.com/anacrolix/torrent/fs/torrentfs.go:205 +0x461
github.com/anacrolix/torrent/fs.(*dirNode).Lookup(0xc427204960, 0x4fa1040, 0xc4273c3140, 0xc4273b0013, 0x9, 0x1, 0x0, 0x4933f60, 0xc427380860)
	<autogenerated>:6 +0xa1
bazil.org/fuse/fs.(*Server).handleRequest(0xc4200f00c0, 0x4fa1040, 0xc4273c3140, 0x4934760, 0xc427204960, 0xc4271e7d40, 0x4938aa0, 0xc4273f48c0, 0xc42526bef8, 0x0, ...)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:1048 +0x37fc
bazil.org/fuse/fs.(*Server).serve(0xc4200f00c0, 0x4938aa0, 0xc4273f48c0)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:878 +0x495
bazil.org/fuse/fs.(*Server).Serve.func1(0xc4200f00c0, 0x4938aa0, 0xc4273f48c0)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:425 +0x6e
created by bazil.org/fuse/fs.(*Server).Serve
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:426 +0x3c4
2017/08/20 20:20:57 serve.go:859: fuse: panic in handler for Lookup [ID=0x10 Node=0x4 Uid=501 Gid=20 Pid=380] ".DS_Store": runtime error: index out of range
goroutine 2152 [running]:
bazil.org/fuse/fs.(*Server).serve.func2(0x4938aa0, 0xc4273f4900, 0xc4269adef8, 0xc42526be57)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:857 +0x1b1
panic(0x4627fc0, 0x495f400)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/panic.go:489 +0x2cf
github.com/anacrolix/torrent/fs.dirNode.Lookup(0xc420019068, 0x6, 0xc42011c0e0, 0xc420070600, 0xc420136c80, 0x4fa1040, 0xc4273c3200, 0xc4273b0020, 0x9, 0x462e860, ...)
	/Users/themihai/go/src/github.com/anacrolix/torrent/fs/torrentfs.go:205 +0x461
github.com/anacrolix/torrent/fs.(*dirNode).Lookup(0xc427204960, 0x4fa1040, 0xc4273c3200, 0xc4273b0020, 0x9, 0x1, 0x0, 0x4933f60, 0xc427380860)
	<autogenerated>:6 +0xa1
bazil.org/fuse/fs.(*Server).handleRequest(0xc4200f00c0, 0x4fa1040, 0xc4273c3200, 0x4934760, 0xc427204960, 0xc4271e7d40, 0x4938aa0, 0xc4273f4900, 0xc4269adef8, 0x0, ...)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:1048 +0x37fc
bazil.org/fuse/fs.(*Server).serve(0xc4200f00c0, 0x4938aa0, 0xc4273f4900)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:878 +0x495
bazil.org/fuse/fs.(*Server).Serve.func1(0xc4200f00c0, 0x4938aa0, 0xc4273f4900)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:425 +0x6e
created by bazil.org/fuse/fs.(*Server).Serve
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:426 +0x3c4
2017/08/20 20:21:04 serve.go:859: fuse: panic in handler for Read [ID=0xd Node=0x4 Uid=501 Gid=20 Pid=380] 0x2 838 @0x0 dir=true fl=0 lock=0 ffl=OpenReadOnly: runtime error: index out of range
goroutine 4028 [running]:
bazil.org/fuse/fs.(*Server).serve.func2(0x4938ba0, 0xc4273253b0, 0xc42526aef8, 0xc42526ae57)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:857 +0x1b1
panic(0x4627fc0, 0x495f400)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/panic.go:489 +0x2cf
github.com/anacrolix/torrent/fs.dirNode.ReadDirAll(0xc420019068, 0x6, 0xc42011c0e0, 0xc420070600, 0xc420136c80, 0x4fa1040, 0xc4272da940, 0x4010203, 0x462dce0, 0x465d4c0, ...)
	/Users/themihai/go/src/github.com/anacrolix/torrent/fs/torrentfs.go:180 +0x367
github.com/anacrolix/torrent/fs.(*dirNode).ReadDirAll(0xc427204960, 0x4fa1040, 0xc4272da940, 0x6140c28, 0xc427204960, 0x301, 0x0, 0x4933f60)
	<autogenerated>:5 +0x84
bazil.org/fuse/fs.(*Server).handleRequest(0xc4200f00c0, 0x4fa1040, 0xc4272da940, 0x4934760, 0xc427204960, 0xc4271e7d40, 0x4938ba0, 0xc4273253b0, 0xc42526aef8, 0x0, ...)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:1209 +0x45a
bazil.org/fuse/fs.(*Server).serve(0xc4200f00c0, 0x4938ba0, 0xc4273253b0)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:878 +0x495
bazil.org/fuse/fs.(*Server).Serve.func1(0xc4200f00c0, 0x4938ba0, 0xc4273253b0)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:425 +0x6e
created by bazil.org/fuse/fs.(*Server).Serve
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:426 +0x3c4
2017/08/20 20:21:04 serve.go:859: fuse: panic in handler for Read [ID=0xe Node=0x4 Uid=501 Gid=20 Pid=380] 0x2 1676 @0x0 dir=true fl=0 lock=0 ffl=OpenReadOnly: runtime error: index out of range
goroutine 4029 [running]:
bazil.org/fuse/fs.(*Server).serve.func2(0x4938ba0, 0xc427325420, 0xc42526aef8, 0xc42526ae57)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:857 +0x1b1
panic(0x4627fc0, 0x495f400)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/panic.go:489 +0x2cf
github.com/anacrolix/torrent/fs.dirNode.ReadDirAll(0xc420019068, 0x6, 0xc42011c0e0, 0xc420070600, 0xc420136c80, 0x4fa1040, 0xc4272daa80, 0x4010203, 0x462dce0, 0x465d4c0, ...)
	/Users/themihai/go/src/github.com/anacrolix/torrent/fs/torrentfs.go:180 +0x367
github.com/anacrolix/torrent/fs.(*dirNode).ReadDirAll(0xc427204960, 0x4fa1040, 0xc4272daa80, 0x6140c28, 0xc427204960, 0x601, 0x0, 0x4933f60)
	<autogenerated>:5 +0x84
bazil.org/fuse/fs.(*Server).handleRequest(0xc4200f00c0, 0x4fa1040, 0xc4272daa80, 0x4934760, 0xc427204960, 0xc4271e7d40, 0x4938ba0, 0xc427325420, 0xc42526aef8, 0x0, ...)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:1209 +0x45a
bazil.org/fuse/fs.(*Server).serve(0xc4200f00c0, 0x4938ba0, 0xc427325420)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:878 +0x495
bazil.org/fuse/fs.(*Server).Serve.func1(0xc4200f00c0, 0x4938ba0, 0xc427325420)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:425 +0x6e
created by bazil.org/fuse/fs.(*Server).Serve
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:426 +0x3c4
2017/08/20 20:21:04 serve.go:859: fuse: panic in handler for Read [ID=0x2 Node=0x4 Uid=501 Gid=20 Pid=380] 0x2 3353 @0x0 dir=true fl=0 lock=0 ffl=OpenReadOnly: runtime error: index out of range
goroutine 4030 [running]:
bazil.org/fuse/fs.(*Server).serve.func2(0x4938ba0, 0xc427325490, 0xc42526aef8, 0xc42526ae57)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:857 +0x1b1
panic(0x4627fc0, 0x495f400)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/panic.go:489 +0x2cf
github.com/anacrolix/torrent/fs.dirNode.ReadDirAll(0xc420019068, 0x6, 0xc42011c0e0, 0xc420070600, 0xc420136c80, 0x4fa1040, 0xc4272dab00, 0x4010203, 0x462dce0, 0x465d4c0, ...)
	/Users/themihai/go/src/github.com/anacrolix/torrent/fs/torrentfs.go:180 +0x367
github.com/anacrolix/torrent/fs.(*dirNode).ReadDirAll(0xc427204960, 0x4fa1040, 0xc4272dab00, 0x6140c28, 0xc427204960, 0xd01, 0x0, 0x4933f60)
	<autogenerated>:5 +0x84
bazil.org/fuse/fs.(*Server).handleRequest(0xc4200f00c0, 0x4fa1040, 0xc4272dab00, 0x4934760, 0xc427204960, 0xc4271e7d40, 0x4938ba0, 0xc427325490, 0xc42526aef8, 0x0, ...)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:1209 +0x45a
bazil.org/fuse/fs.(*Server).serve(0xc4200f00c0, 0x4938ba0, 0xc427325490)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:878 +0x495
bazil.org/fuse/fs.(*Server).Serve.func1(0xc4200f00c0, 0x4938ba0, 0xc427325490)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:425 +0x6e
created by bazil.org/fuse/fs.(*Server).Serve
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:426 +0x3c4
2017/08/20 20:21:06 serve.go:859: fuse: panic in handler for Read [ID=0x14 Node=0x4 Uid=501 Gid=20 Pid=380] 0x2 838 @0x0 dir=true fl=0 lock=0 ffl=OpenReadOnly: runtime error: index out of range
goroutine 4164 [running]:
bazil.org/fuse/fs.(*Server).serve.func2(0x4938ba0, 0xc427314b60, 0xc425269ef8, 0xc425269e57)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:857 +0x1b1
panic(0x4627fc0, 0x495f400)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/panic.go:489 +0x2cf
github.com/anacrolix/torrent/fs.dirNode.ReadDirAll(0xc420019068, 0x6, 0xc42011c0e0, 0xc420070600, 0xc420136c80, 0x4fa1040, 0xc428564f40, 0x4010203, 0x462dce0, 0x465d4c0, ...)
	/Users/themihai/go/src/github.com/anacrolix/torrent/fs/torrentfs.go:180 +0x367
github.com/anacrolix/torrent/fs.(*dirNode).ReadDirAll(0xc427204960, 0x4fa1040, 0xc428564f40, 0x6140c28, 0xc427204960, 0x301, 0x0, 0x4933f60)
	<autogenerated>:5 +0x84
bazil.org/fuse/fs.(*Server).handleRequest(0xc4200f00c0, 0x4fa1040, 0xc428564f40, 0x4934760, 0xc427204960, 0xc4271e7d40, 0x4938ba0, 0xc427314b60, 0xc425269ef8, 0x46c2c26, ...)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:1209 +0x45a
bazil.org/fuse/fs.(*Server).serve(0xc4200f00c0, 0x4938ba0, 0xc427314b60)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:878 +0x495
bazil.org/fuse/fs.(*Server).Serve.func1(0xc4200f00c0, 0x4938ba0, 0xc427314b60)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:425 +0x6e
created by bazil.org/fuse/fs.(*Server).Serve
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:426 +0x3c4
2017/08/20 20:21:06 serve.go:859: fuse: panic in handler for Read [ID=0x13 Node=0x4 Uid=501 Gid=20 Pid=380] 0x2 1676 @0x0 dir=true fl=0 lock=0 ffl=OpenReadOnly: runtime error: index out of range
goroutine 4165 [running]:
bazil.org/fuse/fs.(*Server).serve.func2(0x4938ba0, 0xc427314bd0, 0xc425269ef8, 0xc425269e57)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:857 +0x1b1
panic(0x4627fc0, 0x495f400)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/panic.go:489 +0x2cf
github.com/anacrolix/torrent/fs.dirNode.ReadDirAll(0xc420019068, 0x6, 0xc42011c0e0, 0xc420070600, 0xc420136c80, 0x4fa1040, 0xc428564fc0, 0x4010203, 0x462dce0, 0x465d4c0, ...)
	/Users/themihai/go/src/github.com/anacrolix/torrent/fs/torrentfs.go:180 +0x367
github.com/anacrolix/torrent/fs.(*dirNode).ReadDirAll(0xc427204960, 0x4fa1040, 0xc428564fc0, 0x6140c28, 0xc427204960, 0x601, 0x0, 0x4933f60)
	<autogenerated>:5 +0x84
bazil.org/fuse/fs.(*Server).handleRequest(0xc4200f00c0, 0x4fa1040, 0xc428564fc0, 0x4934760, 0xc427204960, 0xc4271e7d40, 0x4938ba0, 0xc427314bd0, 0xc425269ef8, 0x0, ...)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:1209 +0x45a
bazil.org/fuse/fs.(*Server).serve(0xc4200f00c0, 0x4938ba0, 0xc427314bd0)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:878 +0x495
bazil.org/fuse/fs.(*Server).Serve.func1(0xc4200f00c0, 0x4938ba0, 0xc427314bd0)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:425 +0x6e
created by bazil.org/fuse/fs.(*Server).Serve
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:426 +0x3c4
2017/08/20 20:21:06 serve.go:859: fuse: panic in handler for Read [ID=0x3 Node=0x4 Uid=501 Gid=20 Pid=380] 0x2 3353 @0x0 dir=true fl=0 lock=0 ffl=OpenReadOnly: runtime error: index out of range
goroutine 4166 [running]:
bazil.org/fuse/fs.(*Server).serve.func2(0x4938ba0, 0xc427314c40, 0xc425269ef8, 0xc425269e57)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:857 +0x1b1
panic(0x4627fc0, 0x495f400)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/panic.go:489 +0x2cf
github.com/anacrolix/torrent/fs.dirNode.ReadDirAll(0xc420019068, 0x6, 0xc42011c0e0, 0xc420070600, 0xc420136c80, 0x4fa1040, 0xc428565040, 0x4010203, 0x462dce0, 0x465d4c0, ...)
	/Users/themihai/go/src/github.com/anacrolix/torrent/fs/torrentfs.go:180 +0x367
github.com/anacrolix/torrent/fs.(*dirNode).ReadDirAll(0xc427204960, 0x4fa1040, 0xc428565040, 0x6140c28, 0xc427204960, 0xd01, 0x0, 0x4933f60)
	<autogenerated>:5 +0x84
bazil.org/fuse/fs.(*Server).handleRequest(0xc4200f00c0, 0x4fa1040, 0xc428565040, 0x4934760, 0xc427204960, 0xc4271e7d40, 0x4938ba0, 0xc427314c40, 0xc425269ef8, 0x0, ...)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:1209 +0x45a
bazil.org/fuse/fs.(*Server).serve(0xc4200f00c0, 0x4938ba0, 0xc427314c40)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:878 +0x495
bazil.org/fuse/fs.(*Server).Serve.func1(0xc4200f00c0, 0x4938ba0, 0xc427314c40)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:425 +0x6e
created by bazil.org/fuse/fs.(*Server).Serve
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:426 +0x3c4
2017/08/20 20:24:45 serve.go:859: fuse: panic in handler for Read [ID=0xb Node=0x4 Uid=501 Gid=20 Pid=380] 0x1 838 @0x0 dir=true fl=0 lock=0 ffl=OpenReadOnly: runtime error: index out of range
goroutine 4872 [running]:
bazil.org/fuse/fs.(*Server).serve.func2(0x4938ba0, 0xc42001c070, 0xc420046ef8, 0xc420046e57)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:857 +0x1b1
panic(0x4627fc0, 0x495f400)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/panic.go:489 +0x2cf
github.com/anacrolix/torrent/fs.dirNode.ReadDirAll(0xc420019068, 0x6, 0xc42011c0e0, 0xc420070600, 0xc420136c80, 0x4fa1040, 0xc4273b4640, 0x4010203, 0x462dce0, 0x465d4c0, ...)
	/Users/themihai/go/src/github.com/anacrolix/torrent/fs/torrentfs.go:180 +0x367
github.com/anacrolix/torrent/fs.(*dirNode).ReadDirAll(0xc427204960, 0x4fa1040, 0xc4273b4640, 0x6140c28, 0xc427204960, 0x301, 0x0, 0x4933f60)
	<autogenerated>:5 +0x84
bazil.org/fuse/fs.(*Server).handleRequest(0xc4200f00c0, 0x4fa1040, 0xc4273b4640, 0x4934760, 0xc427204960, 0xc4271e7d40, 0x4938ba0, 0xc42001c070, 0xc420046ef8, 0x0, ...)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:1209 +0x45a
bazil.org/fuse/fs.(*Server).serve(0xc4200f00c0, 0x4938ba0, 0xc42001c070)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:878 +0x495
bazil.org/fuse/fs.(*Server).Serve.func1(0xc4200f00c0, 0x4938ba0, 0xc42001c070)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:425 +0x6e
created by bazil.org/fuse/fs.(*Server).Serve
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:426 +0x3c4
2017/08/20 20:24:45 serve.go:859: fuse: panic in handler for Read [ID=0xe Node=0x4 Uid=501 Gid=20 Pid=380] 0x1 1676 @0x0 dir=true fl=0 lock=0 ffl=OpenReadOnly: runtime error: index out of range
goroutine 4873 [running]:
bazil.org/fuse/fs.(*Server).serve.func2(0x4938ba0, 0xc42001c0e0, 0xc420046ef8, 0xc420046e57)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:857 +0x1b1
panic(0x4627fc0, 0x495f400)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/panic.go:489 +0x2cf
github.com/anacrolix/torrent/fs.dirNode.ReadDirAll(0xc420019068, 0x6, 0xc42011c0e0, 0xc420070600, 0xc420136c80, 0x4fa1040, 0xc4273b47c0, 0x4010203, 0x462dce0, 0x465d4c0, ...)
	/Users/themihai/go/src/github.com/anacrolix/torrent/fs/torrentfs.go:180 +0x367
github.com/anacrolix/torrent/fs.(*dirNode).ReadDirAll(0xc427204960, 0x4fa1040, 0xc4273b47c0, 0x6140c28, 0xc427204960, 0x601, 0x0, 0x4933f60)
	<autogenerated>:5 +0x84
bazil.org/fuse/fs.(*Server).handleRequest(0xc4200f00c0, 0x4fa1040, 0xc4273b47c0, 0x4934760, 0xc427204960, 0xc4271e7d40, 0x4938ba0, 0xc42001c0e0, 0xc420046ef8, 0x0, ...)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:1209 +0x45a
bazil.org/fuse/fs.(*Server).serve(0xc4200f00c0, 0x4938ba0, 0xc42001c0e0)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:878 +0x495
bazil.org/fuse/fs.(*Server).Serve.func1(0xc4200f00c0, 0x4938ba0, 0xc42001c0e0)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:425 +0x6e
created by bazil.org/fuse/fs.(*Server).Serve
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:426 +0x3c4
2017/08/20 20:24:45 serve.go:859: fuse: panic in handler for Read [ID=0xd Node=0x4 Uid=501 Gid=20 Pid=380] 0x1 3353 @0x0 dir=true fl=0 lock=0 ffl=OpenReadOnly: runtime error: index out of range
goroutine 4874 [running]:
bazil.org/fuse/fs.(*Server).serve.func2(0x4938ba0, 0xc42001c150, 0xc420046ef8, 0xc420046e57)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:857 +0x1b1
panic(0x4627fc0, 0x495f400)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/panic.go:489 +0x2cf
github.com/anacrolix/torrent/fs.dirNode.ReadDirAll(0xc420019068, 0x6, 0xc42011c0e0, 0xc420070600, 0xc420136c80, 0x4fa1040, 0xc4273b4840, 0x4010203, 0x462dce0, 0x465d4c0, ...)
	/Users/themihai/go/src/github.com/anacrolix/torrent/fs/torrentfs.go:180 +0x367
github.com/anacrolix/torrent/fs.(*dirNode).ReadDirAll(0xc427204960, 0x4fa1040, 0xc4273b4840, 0x6140c28, 0xc427204960, 0xd01, 0x0, 0x4933f60)
	<autogenerated>:5 +0x84
bazil.org/fuse/fs.(*Server).handleRequest(0xc4200f00c0, 0x4fa1040, 0xc4273b4840, 0x4934760, 0xc427204960, 0xc4271e7d40, 0x4938ba0, 0xc42001c150, 0xc420046ef8, 0x0, ...)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:1209 +0x45a
bazil.org/fuse/fs.(*Server).serve(0xc4200f00c0, 0x4938ba0, 0xc42001c150)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:878 +0x495
bazil.org/fuse/fs.(*Server).Serve.func1(0xc4200f00c0, 0x4938ba0, 0xc42001c150)
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:425 +0x6e
created by bazil.org/fuse/fs.(*Server).Serve
	/Users/themihai/go/src/bazil.org/fuse/fs/serve.go:426 +0x3c4

```

**Comment by anacrolix** [comment]
Thanks for the report. Do the torrents contain trackers? torrentfs had DHT effectively disabled without additional configuration, which I've corrected. If your torrents did not have trackers, there would have been no way to get any peers, thus the apparent stall. Please update and try again.

**Comment by anacrolix** [comment]
Any update on this?

**Comment by themihai** [comment]
I've decided to develop and use a [vfs](https://godoc.org/golang.org/x/tools/godoc/vfs) implementation on top of torrent package instead of torrentfs so I can't test it anymore but I believe the fix works for torrentfs because  `torrent` package works.

**Comment by anacrolix** [comment]
Okay, thanks for the update.
