### ISSUE TITLE
cgo panic

### ISSUE THREAD

**Issue by themihai** [anacrolix/torrent#195]
I've just upgraded to Go 1.9 and it looks like that reading from torrent throws a panic most likely caused by the cgo calls to go-libutp. It doesn't happen all the time(i.e. only the torrent is open/read/closed several times).

```
Assertion failed: (ctx), function utp_create_socket, file utp_internal.cpp, line 2579.
SIGABRT: abort
PC=0x7fffaa81ddd6 m=8 sigcode=0
signal arrived during cgo execution

goroutine 235 [syscall, locked to thread]:
runtime.cgocall(0x49c26b0, 0xc42050ae18, 0x406ae6e)
	/usr/local/Cellar/go/1.9/libexec/src/runtime/cgocall.go:132 +0x92 fp=0xc42050ade8 sp=0xc42050adb0 pc=0x4004ac2
github.com/anacrolix/go-libutp._Cfunc_utp_create_socket(0x0, 0x0)
	github.com/anacrolix/go-libutp/_obj/_cgo_gotypes.go:255 +0x6c fp=0xc42050ae18 sp=0xc42050ade8 pc=0x47c5a8c
github.com/anacrolix/go-libutp.(*Socket).DialContext.func1(0x0, 0xc420290c00)
	/Users/xuser/go/src/github.com/anacrolix/go-libutp/socket.go:180 +0x72 fp=0xc42050ae58 sp=0xc42050ae18 pc=0x47cdc42
github.com/anacrolix/go-libutp.(*Socket).DialContext(0xc4202da000, 0x50a27c0, 0xc4204d0800, 0xc420316aa0, 0x14, 0x0, 0x0, 0x0, 0x0)
	/Users/xuser/go/src/github.com/anacrolix/go-libutp/socket.go:180 +0x126 fp=0xc42050aec8 sp=0xc42050ae58 pc=0x47cb8c6
github.com/anacrolix/torrent.(*Client).dialUTP(0xc42040a700, 0x50a27c0, 0xc4204d0800, 0xc420316aa0, 0x14, 0x317b7d3835353734, 0x694d7d3035363734, 0x2073697a2069612d, 0x75707320692de373)
	/Users/xuser/go/src/github.com/anacrolix/torrent/client.go:532 +0x95 fp=0xc42050af40 sp=0xc42050aec8 pc=0x47d4e35
github.com/anacrolix/torrent.(*Client).dialFirst.func1(0xc42040a700, 0x50a27c0, 0xc4204d0800, 0xc420316aa0, 0x14, 0xc4204fb980)
	/Users/xuser/go/src/github.com/anacrolix/torrent/client.go:547 +0x6e fp=0xc42050afb0 sp=0xc42050af40 pc=0x47ff65e
runtime.goexit()
	/usr/local/Cellar/go/1.9/libexec/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42050afb8 sp=0xc42050afb0 pc=0x4064551
created by github.com/anacrolix/torrent.(*Client).dialFirst
	/Users/xuser/go/src/github.com/anacrolix/torrent/client.go:546 +0x413

goroutine 1 [select, locked to thread]:
x.org/xcomp/tvc/remote.RunKeyboard(0x50a27c0, 0xc42027a100, 0xc4202ec000, 0xc420152a20, 0x1b9e, 0xc420202c40)
	/Users/xuser/go/src/x.org/xcomp/tvc/remote/keyboard.go:19 +0x8e8
main.main()
	/Users/xuser/go/src/x.org/xcomp/tvc/main.go:114 +0x936

goroutine 19 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x5122c00)
	/Users/xuser/go/src/github.com/golang/glog/glog.go:882 +0xc3
created by github.com/golang/glog.init.0
	/Users/xuser/go/src/github.com/golang/glog/glog.go:410 +0x23b

.........................................................................................
......more logs....

goroutine 247 [runnable]:
github.com/anacrolix/torrent.(*Client).dialFirst.func1(0xc42040a700, 0x50a27c0, 0xc4204d0a80, 0xc420316c80, 0x11, 0xc4204fbf80)
	/Users/xuser/go/src/github.com/anacrolix/torrent/client.go:546
created by github.com/anacrolix/torrent.(*Client).dialFirst
	/Users/xuser/go/src/github.com/anacrolix/torrent/client.go:546 +0x413

goroutine 260 [runnable]:
sync.(*Cond).Broadcast-fm()
	/Users/xuser/go/src/github.com/anacrolix/go-libutp/socket.go:74
created by time.goFunc
	/usr/local/Cellar/go/1.9/libexec/src/time/sleep.go:170 +0x52

goroutine 248 [runnable]:
github.com/anacrolix/torrent.(*Client).dialFirst.func2(0xc42040a700, 0x50a27c0, 0xc4204d0a80, 0xc420316c80, 0x11, 0xc4204fbf80)
	/Users/xuser/go/src/github.com/anacrolix/torrent/client.go:553
created by github.com/anacrolix/torrent.(*Client).dialFirst
	/Users/xuser/go/src/github.com/anacrolix/torrent/client.go:553 +0x371

rax    0x0
rbx    0x6
rcx    0x7000069c8d18
rdx    0x0
rdi    0x1f03
rsi    0x6
rbp    0x7000069c8d40
rsp    0x7000069c8d18
r8     0x0
r9     0xa13
r10    0x8000000
r11    0x206
r12    0x7679028
r13    0x7679000
r14    0x7000069c9000
r15    0x50869a8
rip    0x7fffaa81ddd6
rflags 0x206
cs     0x7
fs     0x0
gs     0x0
exit status 2
```

**Comment by anacrolix** [comment]
Thanks for that. It looks like it happens if you Dial on a Socket that's been closed. There should be a check that the Socket is not closed before it makes the call to libutp.

**Comment by axet** [comment]
@anacrolix That why I nil all objects after close.

```diff
	cl.closed.Set()
	if cl.dHT != nil {
		cl.dHT.Close()
		cl.dHT = nil
	}
	if cl.utpSock != nil {
		cl.utpSock.Close()
		cl.utpSock = nil
	}
	if cl.tcpListener != nil {
		cl.tcpListener.Close()
		cl.tcpListener = nil
	}
	for _, t := range cl.torrents {
		t.close()
```

You may need to add checks for half open connections and other to prevent crashes. You can copy related changes from https://gitlab.com/axet/torrent

I can create branch if you care.

**Comment by anacrolix** [comment]
That's okay, I believe Dialing on a closed Socket should just return an error, rather than crashing.

**Comment by anacrolix** [comment]
Fixed in https://github.com/anacrolix/go-libutp/commit/2bf9f9a92044377b8d10b3c8d72c6d00e7ce436e
