### ISSUE TITLE
RateLimiter raising a panic

### ISSUE THREAD

**Issue by elgatito** [anacrolix/torrent#202]
While limiting Upload speed, I get the panic.

Rate limiter:
```		DownloadLimiter: rate.NewLimiter(rate.Inf, 1024),
		UploadLimiter:   rate.NewLimiter(rate.Inf, 1024),
```
bit later, I change it to:
```
s.UploadLimiter.SetLimit(rate.Limit(i))
```
where i = 10240 (10kb), and then adding torrent and so on.

Log:
```
09:05:05.875 T:140291785455360  NOTICE: [plugin.video.elementum] panic: (*rate.Reservation) (0xd50c80,0xc421ced580)
09:05:05.876 T:140291785455360  NOTICE: [plugin.video.elementum]
09:05:05.876 T:140291785455360  NOTICE: [plugin.video.elementum] goroutine 3292 [running]:
09:05:05.878 T:140291785455360  NOTICE: [plugin.video.elementum] github.com/anacrolix/torrent.(*connection).upload(0xc4219fa2c0, 0xc420457020, 0xc420457020)
09:05:05.879 T:140291785455360  NOTICE: [plugin.video.elementum] 	/home/elgatito/go/src/github.com/anacrolix/torrent/connection.go:1091 +0x6d5
09:05:05.879 T:140291785455360  NOTICE: [plugin.video.elementum] github.com/anacrolix/torrent.(*connection).fillWriteBuffer(0xc4219fa2c0, 0xc420457020)
09:05:05.879 T:140291785455360  NOTICE: [plugin.video.elementum] 	/home/elgatito/go/src/github.com/anacrolix/torrent/connection.go:376 +0x34c
09:05:05.880 T:140291785455360  NOTICE: [plugin.video.elementum] github.com/anacrolix/torrent.(*connection).writer(0xc4219fa2c0, 0xdf8475800)
09:05:05.880 T:140291785455360  NOTICE: [plugin.video.elementum] 	/home/elgatito/go/src/github.com/anacrolix/torrent/connection.go:402 +0x5b0
09:05:05.881 T:140291785455360  NOTICE: [plugin.video.elementum] created by github.com/anacrolix/torrent.(*Client).runHandshookConn
09:05:05.881 T:140291785455360  NOTICE: [plugin.video.elementum] 	/home/elgatito/go/src/github.com/anacrolix/torrent/client.go:1038 +0x1a1
```

**Comment by elgatito** [comment]
Tried UploadLimiter with `rate.Inf, 0` and it still throws a panic:

```
10:22:52.484 T:140223268357888  NOTICE: [plugin.video.elementum] panic: (*rate.Reservation) (0xd50a40,0xc423035c80)
10:22:52.484 T:140223268357888  NOTICE: [plugin.video.elementum]
10:22:52.485 T:140223268357888  NOTICE: [plugin.video.elementum] goroutine 4287 [running]:
10:22:52.486 T:140223268357888  NOTICE: [plugin.video.elementum] github.com/anacrolix/torrent.(*connection).upload(0xc42112fb80, 0xc4230de060, 0xc4230de060)
10:22:52.486 T:140223268357888  NOTICE: [plugin.video.elementum] 	/home/elgatito/go/src/github.com/anacrolix/torrent/connection.go:1091 +0x6d5
10:22:52.487 T:140223268357888  NOTICE: [plugin.video.elementum] github.com/anacrolix/torrent.(*connection).fillWriteBuffer(0xc42112fb80, 0xc4230de060)
10:22:52.489 T:140223268357888  NOTICE: [plugin.video.elementum] 	/home/elgatito/go/src/github.com/anacrolix/torrent/connection.go:376 +0x34c
10:22:52.490 T:140223268357888  NOTICE: [plugin.video.elementum] github.com/anacrolix/torrent.(*connection).writer(0xc42112fb80, 0xdf8475800)
10:22:52.492 T:140223268357888  NOTICE: [plugin.video.elementum] 	/home/elgatito/go/src/github.com/anacrolix/torrent/connection.go:402 +0x5b0
10:22:52.492 T:140223268357888  NOTICE: [plugin.video.elementum] created by github.com/anacrolix/torrent.(*Client).runHandshookConn
10:22:52.494 T:140223268357888  NOTICE: [plugin.video.elementum] 	/home/elgatito/go/src/github.com/anacrolix/torrent/client.go:1038 +0x1a1
```

Tried with NoUpload: true, Seed: false, and getting no errors....

**Comment by elgatito** [comment]
```
diff --git a/connection.go b/connection.go
index faa7c92..3e10b0a 100644
--- a/connection.go
+++ b/connection.go
@@ -14,6 +14,8 @@ import (
        "sync"
        "time"
 
+       "golang.org/x/time/rate"
+
        "github.com/anacrolix/torrent/mse"
 
        "github.com/anacrolix/missinggo"
@@ -1086,20 +1088,22 @@ another:
                        return false
                }
                for r := range c.PeerRequests {
-                       res := cl.uploadLimit.ReserveN(time.Now(), int(r.Length))
-                       if !res.OK() {
-                               panic(res)
-                       }
-                       delay := res.Delay()
-                       if delay > 0 {
-                               res.Cancel()
-                               if c.uploadTimer == nil {
-                                       c.uploadTimer = time.AfterFunc(delay, c.writerCond.Broadcast)
-                               } else {
-                                       c.uploadTimer.Reset(delay)
+                       if cl.uploadLimit.Limit() != rate.Inf {
+                               res := cl.uploadLimit.ReserveN(time.Now(), int(r.Length))
+                               if !res.OK() {
+                                       panic(res)
+                               }
+                               delay := res.Delay()
+                               if delay > 0 {
+                                       res.Cancel()
+                                       if c.uploadTimer == nil {
+                                               c.uploadTimer = time.AfterFunc(delay, c.writerCond.Broadcast)
+                                       } else {
+                                               c.uploadTimer.Reset(delay)
+                                       }
+                                       // Hard to say what to return here.
+                                       return true
                                }
-                               // Hard to say what to return here.
-                               return true
                        }
                        more, err := cl.sendChunk(t, c, r, msg)
                        if err != nil {

```

I can't test it, and I don't quite understand the RateLimiter, but it looks like we don't need to reserve upload if it's `rate.Inf`.

**Comment by anacrolix** [comment]
Ah, see the comment for UploadRateLimiter: https://godoc.org/github.com/anacrolix/torrent#Config. The default chunk size is 16kb, which means the upload burst limit must be >= 16kb. I should improve the panic message. Please try with a higher burst limit and let me know if it fixes the problem for you.

**Comment by elgatito** [comment]
According to the comment, Download also should be >= 16kb?

**Comment by anacrolix** [comment]
Yes I believe so. I haven't tested this as far as I'm aware as there is a very complex chain of nested Reader and Writers around the raw connections to manage stats, buffering, counters etc, so it would depend on their implementations. However a burst of 16KiB is very small as it is, I don't believe going smaller than that gives much benefit worth investigating. The comment on the download rate limiter should contain the most important parameters to be considered.

**Comment by anacrolix** [comment]
I believe this has been addressed.
