### ISSUE TITLE
torrent CLI tool stops with error after sometime

### ISSUE THREAD

**Issue by karuppiah7890** [anacrolix/torrent#205]
This occurs suddenly or sometimes later. It happened quite a few times with a `panic`. Here's the log

```
$ torrent 'magnet:?xt=urn:btih:KRWPCX3SJUM4IMM4YF5RPHL6ANPYTQPU'
ubuntu-14.04.2-desktop-amd64.iso [====>---------------------------------------------------------------]   9% downloading (98 MB/1.0 GB))

panic: interface conversion: interface {} is *[]int, not []int

goroutine 13182 [running]:
github.com/anacrolix/torrent.(*Torrent).getConnPieceInclination(0xc42015b680, 0x83cc19, 0xc42018fd10, 0x4)
	/root/go/src/github.com/anacrolix/torrent/torrent.go:1000 +0x113
github.com/anacrolix/torrent.(*connection).getPieceInclination(0xc42018fb80, 0x4, 0x976901, 0x1)
	/root/go/src/github.com/anacrolix/torrent/connection.go:631 +0x78
github.com/anacrolix/torrent.(*connection).updatePiecePriority(0xc42018fb80, 0x4, 0x700)
	/root/go/src/github.com/anacrolix/torrent/connection.go:611 +0x9a
github.com/anacrolix/torrent.(*connection).peerPiecesChanged(0xc42018fb80)
	/root/go/src/github.com/anacrolix/torrent/connection.go:648 +0x9e
github.com/anacrolix/torrent.(*connection).peerSentBitfield(0xc42018fb80, 0xc420094400, 0x7c8, 0x900, 0xc420073caa, 0x1)
	/root/go/src/github.com/anacrolix/torrent/connection.go:697 +0x136
github.com/anacrolix/torrent.(*connection).mainReadLoop(0xc42018fb80, 0xc42018fb80, 0xc42015b680)
	/root/go/src/github.com/anacrolix/torrent/connection.go:866 +0x623
github.com/anacrolix/torrent.(*Client).runHandshookConn(0xc420160e00, 0xc42018fb80, 0xc42015b680, 0x0)
	/root/go/src/github.com/anacrolix/torrent/client.go:1028 +0x1d4
github.com/anacrolix/torrent.(*Client).runReceivedConn(0xc420160e00, 0xc42018fb80)
	/root/go/src/github.com/anacrolix/torrent/client.go:1015 +0x1db
github.com/anacrolix/torrent.(*Client).incomingConnection(0xc420160e00, 0xed9540, 0xc4208f1a40, 0x1)
	/root/go/src/github.com/anacrolix/torrent/client.go:461 +0x31f
created by github.com/anacrolix/torrent.(*Client).acceptConnections
	/root/go/src/github.com/anacrolix/torrent/client.go:449 +0x315
```

**Comment by anacrolix** [comment]
Thanks for the report. It is probably an oversight in my last commit. I'll fix it in a sec.
