### ISSUE TITLE
Panic while downloading

### ISSUE THREAD

**Issue by elgatito** [anacrolix/torrent#214]
Have got a panic myself while downloading for a minute or so.

Log cut: http://paste.ubuntu.com/26090580/

It was very strange behavior, started very slowly, about 50-150 kb/s while having 1000 peers and 50mbit channel, then got up to 1 MB/sec and then a panic arised.

**Comment by elgatito** [comment]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xa2bb2e]

goroutine 23649 [running]:
github.com/anacrolix/torrent.(*Torrent).numTotalPeers(0xc4200a6000, 0xe7d4e8)
	/home/elgatito/go/src/github.com/anacrolix/torrent/torrent.go:1344 +0x11e
github.com/anacrolix/torrent.(*Torrent).Stats(0xc4200a6000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/elgatito/go/src/github.com/anacrolix/torrent/torrent.go:1335 +0xd6
github.com/elgatito/elementum/bittorrent.(*Torrent).progressEvent(0xc420fca2c0)
	/home/elgatito/go/src/github.com/elgatito/elementum/bittorrent/torrent.go:345 +0x8b
created by github.com/elgatito/elementum/bittorrent.(*Torrent).Watch
	/home/elgatito/go/src/github.com/elgatito/elementum/bittorrent/torrent.go:199 +0x628
```
Another panic while getting Torrent.Stats(), strange...

**Comment by elgatito** [comment]
This one with the latest code:
http://paste.ubuntu.com/26090703/

**Comment by anacrolix** [comment]
Okay both should be fixed, thanks.
