### ISSUE TITLE
Panic from outgoingConnection

### ISSUE THREAD

**Issue by elgatito** [anacrolix/torrent#228]
User have reported he gets this error from time to time. elgatito/plugin.video.elementum#39
Probably related to the library?

```
22:53:48.674 T:18446744071702055200  NOTICE: [plugin.video.elementum] panic: runtime error: index out of range
22:53:48.675 T:18446744071702055200  NOTICE: [plugin.video.elementum]
22:53:48.676 T:18446744071702055200  NOTICE: [plugin.video.elementum] goroutine 9135 [running]:
22:53:48.677 T:18446744071702055200  NOTICE: [plugin.video.elementum] github.com/anacrolix/torrent.(*Torrent).piecePriority(...)
22:53:48.680 T:18446744071702055200  NOTICE: [plugin.video.elementum]   /ext-go/2/src/github.com/anacrolix/torrent/torrent.go:938
22:53:48.682 T:18446744071702055200  NOTICE: [plugin.video.elementum] github.com/anacrolix/torrent.(*connection).updatePiecePriority(0x89952960, 0xffffffff, 0x1)
22:53:48.683 T:18446744071702055200  NOTICE: [plugin.video.elementum]   /ext-go/2/src/github.com/anacrolix/torrent/connection.go:609 +0x1c0
22:53:48.686 T:18446744071702055200  NOTICE: [plugin.video.elementum] github.com/anacrolix/torrent.(*connection).peerSentHave(0x89952960, 0xffffffff, 0x1, 0x1)
22:53:48.688 T:18446744071702055200  NOTICE: [plugin.video.elementum]   /ext-go/2/src/github.com/anacrolix/torrent/connection.go:678 +0xa8
22:53:48.690 T:18446744071702055200  NOTICE: [plugin.video.elementum] github.com/anacrolix/torrent.(*connection).mainReadLoop(0x89952960, 0x89952960, 0x896f91e0)
22:53:48.691 T:18446744071702055200  NOTICE: [plugin.video.elementum]   /ext-go/2/src/github.com/anacrolix/torrent/connection.go:843 +0x320
22:53:48.694 T:18446744071702055200  NOTICE: [plugin.video.elementum] github.com/anacrolix/torrent.(*Client).runHandshookConn(0x89454480, 0x89952960, 0x896f91e0, 0x89a4ff01)
22:53:48.695 T:18446744071702055200  NOTICE: [plugin.video.elementum]   /ext-go/2/src/github.com/anacrolix/torrent/client.go:849 +0x190
22:53:48.697 T:18446744071702055200  NOTICE: [plugin.video.elementum] github.com/anacrolix/torrent.(*Client).runInitiatedHandshookConn(0x89454480, 0x89952960, 0x896f91e0)
22:53:48.698 T:18446744071702055200  NOTICE: [plugin.video.elementum]   /ext-go/2/src/github.com/anacrolix/torrent/client.go:809 +0xf4
22:53:48.700 T:18446744071702055200  NOTICE: [plugin.video.elementum] github.com/anacrolix/torrent.(*Client).outgoingConnection(0x89454480, 0x896f91e0, 0x89879680, 0x13, 0xa9fac112, 0x2)
22:53:48.701 T:18446744071702055200  NOTICE: [plugin.video.elementum]   /ext-go/2/src/github.com/anacrolix/torrent/client.go:700 +0x194
22:53:48.702 T:18446744071702055200  NOTICE: [plugin.video.elementum] created by github.com/anacrolix/torrent.(*Client).initiateConn
22:53:48.704 T:18446744071702055200  NOTICE: [plugin.video.elementum]   /ext-go/2/src/github.com/anacrolix/torrent/client.go:519 +0x1f0
```

**Comment by anacrolix** [comment]
It's probably a peer sending a ridiculously large piece index that's being cast to a negative value if it's a 32-bit system. I'll make a fix that should screen these bad values in the short term, and in the long term I'll try to remove some of the casting.
