### ISSUE TITLE
BEP 40 implementation causes confluence to crash

### ISSUE THREAD

**Issue by Ivshti** [anacrolix/torrent#244]
Stack trace:

```
goroutine 1610 [running]:
github.com/anacrolix/torrent.bep40PriorityBytes(0x0, 0x0, 0x0, 0xc357, 0xc42017d328, 0x4, 0x4, 0xc357, 0x0, 0xc4204d97b8, ...)
	/home/ivo/go/src/github.com/anacrolix/torrent/bep40.go:71 +0x9d9
github.com/anacrolix/torrent.bep40Priority(0x0, 0x0, 0x0, 0xc357, 0xc42017d328, 0x4, 0x4, 0x44c357, 0x0)
	/home/ivo/go/src/github.com/anacrolix/torrent/bep40.go:75 +0x9b
github.com/anacrolix/torrent.(*Client).newTorrent.func1(0x0, 0x0, 0x0, 0xc42017d328, 0x4, 0x4, 0xc357, 0xa76321, 0x2, 0x0, ...)
	/home/ivo/go/src/github.com/anacrolix/torrent/client.go:1036 +0xd8
github.com/anacrolix/torrent.(*prioritizedPeers).Add(0xc4200e8180, 0x0, 0x0, 0x0, 0xc42017d328, 0x4, 0x4, 0xc357, 0xa76321, 0x2, ...)
	/home/ivo/go/src/github.com/anacrolix/torrent/prioritized_peers.go:34 +0x5e
github.com/anacrolix/torrent.(*Torrent).addPeer(0xc4200e8000, 0x0, 0x0, 0x0, 0xc42017d328, 0x4, 0x4, 0xc357, 0xa76321, 0x2, ...)
	/home/ivo/go/src/github.com/anacrolix/torrent/torrent.go:256 +0xf0
github.com/anacrolix/torrent.(*Torrent).addPeers(0xc4200e8000, 0xc420569ae0, 0x1, 0x1)
	/home/ivo/go/src/github.com/anacrolix/torrent/torrent.go:1420 +0xbf
github.com/anacrolix/torrent.(*Torrent).consumeDHTAnnounce(0xc4200e8000, 0xc4203503c0)
	/home/ivo/go/src/github.com/anacrolix/torrent/torrent.go:1369 +0x380
github.com/anacrolix/torrent.(*Torrent).announceDHT(0xc4200e8000, 0x1, 0x0, 0x0)
	/home/ivo/go/src/github.com/anacrolix/torrent/torrent.go:1387 +0xd0
github.com/anacrolix/torrent.(*Torrent).dhtAnnouncer(0xc4200e8000)
	/home/ivo/go/src/github.com/anacrolix/torrent/torrent.go:1400 +0x173
created by github.com/anacrolix/torrent.(*Client).AddTorrentInfoHashWithStorage
	/home/ivo/go/src/github.com/anacrolix/torrent/client.go:1083 +0x1e3
```

Requests that trigger this:

http://localhost:8070/data?ih=7782ab24188091eae3f61fd218b2dffb4bf9cf9c

http://localhost:8070/info?ih=7782ab24188091eae3f61fd218b2dffb4bf9cf9c

Temporary workaround I did:

Revert anacrolix/torrent to ed80150f08e0b492f7fd82a1d492b58048e784df

Revert confluence to ed7ced6b60baca51190a93114c6764c44850075a

**Comment by anacrolix** [comment]
Thanks for the report. Are you using both IPv4 and IPv6 on your confluence instance? Can you provide the contents of the panic?

**Comment by Ivshti** [comment]
I do have both ipv4 and ipv6 enabled on the machines(s) - tested it on two. 

What do you mean "contents"?

**Comment by muesli** [comment]
@anacrolix In my case `a.IP` is nil, while `b.IP` is a valid IPv4.
