### ISSUE TITLE
assertNoPendingRequests: panic -1

### ISSUE THREAD

**Issue by themihai** [anacrolix/torrent#249]
Sometimes the client panics (see below). I'm not sure what condition triggers it. The torrent seems unresponsive(I can only read few bytes at the beginning) and after a while I get this panic.

```

panic: -1

goroutine 394908 [running]:
github.com/anacrolix/torrent.(*Torrent).assertNoPendingRequests(0xc4201f0380)
	/Users/themihai/go/src/github.com/anacrolix/torrent/torrent.go:1230 +0xec
github.com/anacrolix/torrent.(*Torrent).deleteConnection(0xc4201f0380, 0xc42026e500, 0xc422635ed0)
	/Users/themihai/go/src/github.com/anacrolix/torrent/torrent.go:1222 +0xd5
github.com/anacrolix/torrent.(*Torrent).dropConnection(0xc4201f0380, 0xc42026e500)
	/Users/themihai/go/src/github.com/anacrolix/torrent/torrent.go:1238 +0x5d
github.com/anacrolix/torrent.(*Client).runHandshookConn(0xc420352a80, 0xc42026e500, 0xc4201f0380, 0x1)
	/Users/themihai/go/src/github.com/anacrolix/torrent/client.go:794 +0x383
github.com/anacrolix/torrent.(*Client).outgoingConnection(0xc420352a80, 0xc4201f0380, 0xc420aa0f00, 0x14, 0x4b8ca5d, 0x2)
	/Users/themihai/go/src/github.com/anacrolix/torrent/client.go:648 +0x1d8
created by github.com/anacrolix/torrent.(*Torrent).initiateConn
	/Users/themihai/go/src/github.com/anacrolix/torrent/torrent.go:1733 +0x2b8

```

**Comment by themihai** [comment]
I run `go get github.com/anacrolix/torrent` to make sure I'm using the HEAD. The package still panics but I cannot create a reproducible test case.
   I believe it panics when the client is "idle"(nothing is downloaded), perhaps seeding. 

```
panic: -1

goroutine 10544 [running]:
github.com/anacrolix/torrent.(*Torrent).assertNoPendingRequests(0xc42079ca80)
	/Users/themihai/go/src/github.com/anacrolix/torrent/torrent.go:1232 +0xec
github.com/anacrolix/torrent.(*Torrent).deleteConnection(0xc42079ca80, 0xc4201e1900, 0xc421715ed0)
	/Users/themihai/go/src/github.com/anacrolix/torrent/torrent.go:1224 +0xd5
github.com/anacrolix/torrent.(*Torrent).dropConnection(0xc42079ca80, 0xc4201e1900)
	/Users/themihai/go/src/github.com/anacrolix/torrent/torrent.go:1240 +0x5d
github.com/anacrolix/torrent.(*Client).runHandshookConn(0xc42013ae00, 0xc4201e1900, 0xc42079ca80, 0x1)
	/Users/themihai/go/src/github.com/anacrolix/torrent/client.go:794 +0x383
github.com/anacrolix/torrent.(*Client).outgoingConnection(0xc42013ae00, 0xc42079ca80, 0xc421528160, 0x12, 0x4b8e3bd, 0x2)
	/Users/themihai/go/src/github.com/anacrolix/torrent/client.go:648 +0x1d8
created by github.com/anacrolix/torrent.(*Torrent).initiateConn
	/Users/themihai/go/src/github.com/anacrolix/torrent/torrent.go:1735 +0x2b8
```

**Comment by anacrolix** [comment]
Thanks for the report. A few people are seeing this but I'm still unable to reproduce. How long do you think between downloading and the assertion being triggered (the idle time?)?

**Comment by themihai** [comment]
I'll let you know once I figure it now. The behaviour is difficult to reproduce.
