### ISSUE TITLE
huge file seed error

### ISSUE THREAD

**Issue by unix2dos** [anacrolix/torrent#259]
i use an client seeding,  the file is 10G, piece length is 256KB,  so has many pieces
another client download,  use <-gotinfo(),  but got this wrong
```
incomes-server.1 | goroutine 14818 [semacquire]:
incomes-server.1 | sync.runtime_SemacquireMutex(0xc42015a534, 0x0)
incomes-server.1 | 	/usr/local/go/src/runtime/sema.go:71 +0x3d
incomes-server.1 | sync.(*Mutex).Lock(0xc42015a530)
incomes-server.1 | 	/usr/local/go/src/sync/mutex.go:134 +0xee
incomes-server.1 | sync.(*RWMutex).Lock(0xc42015a530)
incomes-server.1 | 	/usr/local/go/src/sync/rwmutex.go:93 +0x2d
incomes-server.1 | github.com/anacrolix/sync.(*RWMutex).Lock(0xc42015a400)
incomes-server.1 | 	/Users/liuwei/golang/src/github.com/anacrolix/sync/rwmutex.go:18 +0x58
incomes-server.1 | github.com/anacrolix/torrent.(*Torrent).verifyPiece(0xc420384000, 0x3979)
incomes-server.1 | 	/Users/liuwei/golang/src/github.com/anacrolix/torrent/torrent.go:1669 +0x3c
incomes-server.1 | created by github.com/anacrolix/torrent.(*Torrent).queuePieceCheck
incomes-server.1 | 	/Users/liuwei/golang/src/github.com/anacrolix/torrent/torrent.go:1724 +0xea
incomes-server.1 |
incomes-server.1 | goroutine 14819 [semacquire]:
incomes-server.1 | sync.runtime_SemacquireMutex(0xc42015a534, 0x4600)
incomes-server.1 | 	/usr/local/go/src/runtime/sema.go:71 +0x3d
incomes-server.1 | sync.(*Mutex).Lock(0xc42015a530)
incomes-server.1 | 	/usr/local/go/src/sync/mutex.go:134 +0xee
incomes-server.1 | sync.(*RWMutex).Lock(0xc42015a530)
incomes-server.1 | 	/usr/local/go/src/sync/rwmutex.go:93 +0x2d
incomes-server.1 | github.com/anacrolix/sync.(*RWMutex).Lock(0xc42015a400)
incomes-server.1 | 	/Users/liuwei/golang/src/github.com/anacrolix/sync/rwmutex.go:18 +0x58
incomes-server.1 | github.com/anacrolix/torrent.(*Torrent).verifyPiece(0xc420384000, 0x397a)
incomes-server.1 | 	/Users/liuwei/golang/src/github.com/anacrolix/torrent/torrent.go:1669 +0x3c
incomes-server.1 | created by github.com/anacrolix/torrent.(*Torrent).queuePieceCheck
incomes-server.1 | 	/Users/liuwei/golang/src/github.com/anacrolix/torrent/torrent.go:1724 +0xea
```

**Comment by anacrolix** [comment]
I'm not sure what the issue is. Are you getting a panic or deadlock or something else?

**Comment by unix2dos** [comment]
huge file seed will stuck my computer, this is `lsof` show

```
COMMAND     PID   USER   FD      TYPE             DEVICE   SIZE/OFF    NODE NAME
incomes-c 49898 liuwei  cwd       DIR                1,8        816 7716289 /Users/liuwei/golang/src/fhyx/kinema-client
incomes-c 49898 liuwei  txt       REG                1,8   24147728 9679332 /Users/liuwei/golang/bin/incomes-client
incomes-c 49898 liuwei  txt       REG                1,8     131072 9680436 /Users/liuwei/golang/src/fhyx/kinema-client/Sync/.torrent.bolt.db
incomes-c 49898 liuwei  txt       REG                1,8     697712 7536780 /usr/lib/dyld
incomes-c 49898 liuwei    0r      CHR                3,2        0t0     312 /dev/null
incomes-c 49898 liuwei    1      PIPE 0x30077a1c767bb6a9      16384         ->0x30077a1c767bbb29
incomes-c 49898 liuwei    2      PIPE 0x30077a1c767bb9a9      16384         ->0x30077a1c767bca29
incomes-c 49898 liuwei    3u      REG                1,8     131072 9680436 /Users/liuwei/golang/src/fhyx/kinema-client/Sync/.torrent.bolt.db
incomes-c 49898 liuwei    4u   KQUEUE                                       count=0, state=0xa
incomes-c 49898 liuwei    5r      CHR               14,1     0t4096     587 /dev/urandom
incomes-c 49898 liuwei    6u     IPv4 0x30077a1c7c9ee5a9        0t0     TCP *:60484 (LISTEN)
incomes-c 49898 liuwei    7u     IPv4 0x30077a1c6cd9ba09        0t0     UDP *:60484
incomes-c 49898 liuwei    8u     IPv6 0x30077a1c68bab189        0t0     TCP *:16280 (LISTEN)
incomes-c 49898 liuwei    9r      REG                1,8 4606373834 9637047 /Users/liuwei/bak/4_61G.zip
incomes-c 49898 liuwei   10r      REG                1,8 4606373834 9637047 /Users/liuwei/bak/4_61G.zip
incomes-c 49898 liuwei   11r      REG                1,8 4606373834 9637047 /Users/liuwei/bak/4_61G.zip
incomes-c 49898 liuwei   12r      REG                1,8 4606373834 9637047 /Users/liuwei/bak/4_61G.zip
incomes-c 49898 liuwei   13r      REG                1,8 4606373834 9637047 /Users/liuwei/bak/4_61G.zip
incomes-c 49898 liuwei   14r      REG                1,8 4606373834 9637047 /Users/liuwei/bak/4_61G.zip
incomes-c 49898 liuwei   15r      REG                1,8 4606373834 9637047 /Users/liuwei/bak/4_61G.zip
incomes-c 49898 liuwei   16r      REG                1,8 4606373834 9637047 /Users/liuwei/bak/4_61G.zip
incomes-c 49898 liuwei   17r      REG                1,8 4606373834 9637047 /Users/liuwei/bak/4_61G.zip
incomes-c 49898 liuwei   18r      REG                1,8 4606373834 9637047 /Users/liuwei/bak/4_61G.zip
incomes-c 49898 liuwei   19r      REG                1,8 4606373834 9637047 /Users/liuwei/bak/4_61G.zip
incomes-c 49898 liuwei   20r      REG                1,8 4606373834 9637047 /Users/liuwei/bak/4_61G.zip
incomes-c 49898 liuwei   21r      REG                1,8 4606373834 9637047 /Users/liuwei/bak/4_61G.zip
incomes-c 49898 liuwei   22r      REG                1,8 4606373834 9637047 /Users/liuwei/bak/4_61G.zip
incomes-c 49898 liuwei   23r      REG                1,8 4606373834 9637047 /Users/liuwei/bak/4_61G.zip
incomes-c 49898 liuwei   24r      REG                1,8 4606373834 9637047 /Users/liuwei/bak/4_61G.zip
incomes-c 49898 liuwei   25r      REG                1,8 4606373834 9637047 /Users/liuwei/bak/4_61G.zip
incomes-c 49898 liuwei   26r      REG                1,8 4606373834 9637047 /Users/liuwei/bak/4_61G.zip
incomes-c 49898 liuwei   27r      REG                1,8 4606373834 9637047 /Users/liuwei/bak/4_61G.zip
incomes-c 49898 liuwei   28r      REG                1,8 4606373834 9637047 /Users/liuwei/bak/4_61G.zip
incomes-c 49898 liuwei   29r      REG                1,8 4606373834 9637047 /Users/liuwei/bak/4_61G.zip
incomes-c 49898 liuwei   30r      REG                1,8 4606373834 9637047 /Users/liuwei/bak/4_61G.zip
incomes-c 49898 liuwei   31r      REG                1,8 4606373834 9637047 /Users/liuwei/bak/4_61G.zip
incomes-c 49898 liuwei   32r      REG                1,8 4606373834 9637047 /Users/liuwei/bak/4_61G.zip
incomes-c 49898 liuwei   33r      REG                1,8 4606373834 9637047 /Users/liuwei/bak/4_61G.zip
incomes-c 49898 liuwei   34r      REG                1,8 4606373834 9637047 /Users/liuwei/bak/4_61G.zip
```

**Comment by unix2dos** [comment]
my problem is huge file's piece length
if small will goroutine erro
if big  will stuck computer

**Comment by anacrolix** [comment]
Can you link to some code?

**Comment by unix2dos** [comment]
```
func (t *Torrent) verifyPiece(piece int) {
	cl := t.cl
	cl.mu.Lock()
	defer cl.mu.Unlock()
	p := &t.pieces[piece]
	defer func() {
		p.numVerifies++
		cl.event.Broadcast()
	}()
	for p.hashing || t.storage == nil {
		cl.event.Wait()
	}
	if !p.t.piecesQueuedForHash.Remove(piece) {
		panic("piece was not queued")
	}
	if t.closed.IsSet() || t.pieceComplete(piece) {
		t.updatePiecePriority(piece)
		return
	}
	p.hashing = true
	t.publishPieceChange(piece)
	t.storageLock.RLock()
	cl.mu.Unlock()
	sum := t.hashPiece(piece)
	t.storageLock.RUnlock()
	cl.mu.Lock()
	p.hashing = false
	t.pieceHashed(piece, sum == p.hash)
	t.publishPieceChange(piece)
}
```
if i replace` t.storageLock.RLock()` to ` t.storageLock.Lock()`  huge file will run well.

`sum := t.hashPiece(piece)` will call storage.Piece ReadAt(), and os.Open huge file many a time

this will stuck my computer

**Comment by unix2dos** [comment]
that's some of my own random files, copy and copy to 10G and zip, i use sync in private network. 

if piecelength bigger will stuck computer. i use imac, this problem will appear. but in my macbook 10G files no problem , because whether ssd hard disk?

**Comment by anacrolix** [comment]
Did you work around this? I did intend to fix something here.

**Comment by anacrolix** [comment]
I think this would be fixed after the piece checking queueing being implemented correctly recently.
