### ISSUE TITLE
fatal error: invalid stack pointer in dht.go

### ISSUE THREAD

**Issue by ccampbell** [anacrolix/torrent#28]
I have been running into another panic. It seems to be intermittent and might only be happening on one file.  The full stack trace was over 3000 lines of code, but I think the relevant bit is this:

```
runtime: bad pointer in frame github.com/anacrolix/torrent/dht.(*Server).processPacket at 0xc82384be38: 0x10
fatal error: invalid stack pointer
```

trace

```
goroutine 10 [copystack]:
runtime.assertE2T2(0x7f93e0, 0x7f93e0, 0xc8207071b0, 0xc8239cde48, 0xc823952bf8)
    /usr/local/go/src/runtime/iface.go:233 fp=0xc82384bda0 sp=0xc82384bd98
github.com/anacrolix/torrent/dht.(*Server).processPacket(0xc8200f20f0, 0xc820104000, 0x45, 0x10000, 0x7f3af3c1e158, 0xc823a66f80)
    /home/craig/go/src/github.com/anacrolix/torrent/dht/dht.go:639 +0x278 fp=0xc82384be88 sp=0xc82384bda0
github.com/anacrolix/torrent/dht.(*Server).serve(0xc8200f20f0, 0x0, 0x0)
    /home/craig/go/src/github.com/anacrolix/torrent/dht/dht.go:675 +0x312 fp=0xc82384bf60 sp=0xc82384be88
github.com/anacrolix/torrent/dht.NewServer.func1(0xc8200240d0)
    /home/craig/go/src/github.com/anacrolix/torrent/dht/dht.go:148 +0x28 fp=0xc82384bf98 sp=0xc82384bf60
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82384bfa0 sp=0xc82384bf98
created by github.com/anacrolix/torrent/dht.NewServer
    /home/craig/go/src/github.com/anacrolix/torrent/dht/dht.go:157 +0x283
```

It could totally be me doing something dumb on my end again, but I'm not sure. I'd be happy to provide additional info if it will help.

**Comment by anacrolix** [comment]
This is a bug in Go. I'll link you to it when I'm at a desktop.

**Comment by ccampbell** [comment]
Thanks @anacrolix, do you have the link?

**Comment by anacrolix** [comment]
https://github.com/golang/go/issues/12253

**Comment by anacrolix** [comment]
I had this crash again, I've just pulled the fix they made, I'll see how it goes in production.

**Comment by anacrolix** [comment]
Hasn't happened again with Go 1.5.
