### ISSUE TITLE
Crash in latest version

### ISSUE THREAD

**Issue by ccampbell** [anacrolix/torrent#33]
I know you just closed out one of my previous ones. I am now getting a new one. It is consistently reproducible with certain magnet urls.

```
panic: lame
	panic: sync: Unlock of unlocked RWMutex

goroutine 176 [running]:
sync.(*RWMutex).Unlock(0xc82012a238)
	/usr/local/Cellar/go/1.5/libexec/src/sync/rwmutex.go:114 +0xa3
github.com/anacrolix/sync.(*RWMutex).Unlock(0xc82012a108)
	/Users/craig/go/src/github.com/anacrolix/sync/rwmutex.go:26 +0x57
github.com/anacrolix/torrent.(*torrent).hashPiece(0xc8202f8b00, 0x21, 0x0, 0x0, 0x0)
	/Users/craig/go/src/github.com/anacrolix/torrent/torrent.go:676 +0x49f
github.com/anacrolix/torrent.(*Client).verifyPiece(0xc82012a000, 0xc8202f8b00, 0x21)
	/Users/craig/go/src/github.com/anacrolix/torrent/client.go:2716 +0x1c2
created by github.com/anacrolix/torrent.(*Client).queuePieceCheck
	/Users/craig/go/src/github.com/anacrolix/torrent/client.go:119 +0xb6
```

**Comment by ccampbell** [comment]
I think it is something related to b0b57948902f85cb3445c28c8a70c24534ad2abc

I was able to git checkout the previous revision and build from that, and now I'm not having the problem anymore.

**Comment by anacrolix** [comment]
Thanks for the report. Do you want to PM or share some of the magnet URLs, so I can verify a fix?
