### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by AlexSpain** [anacrolix/torrent#336]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf4b622]

goroutine 26 [running]:
github.com/CortexFoundation/CortexTheseus/vendor/github.com/anacrolix/torrent.(*Client).lock(0x0)
        /mine2/CortexTheseus-1.6.0/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/vendor/github.com/anacrolix/torrent/client.go:1360 +0x22
github.com/CortexFoundation/CortexTheseus/vendor/github.com/anacrolix/torrent.(*Client).AddTorrentInfoHashWithStorage(0x0, 0xd21c8c2219ad4531, 0x1c6cf2724e3151d0, 0x27f7be7, 0x1758dc0, 0xc420293350, 0x0, 0xc420063d00)
        /mine2/CortexTheseus-1.6.0/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/vendor/github.com/anacrolix/torrent/client.go:1060 +0x46
github.com/CortexFoundation/CortexTheseus/vendor/github.com/anacrolix/torrent.(*Client).AddTorrentSpec(0x0, 0xc4201c6230, 0x0, 0x0, 0x0, 0x0)
        /mine2/CortexTheseus-1.6.0/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/vendor/github.com/anacrolix/torrent/client.go:1087 +0x88
github.com/CortexFoundation/CortexTheseus/torrentfs.(*TorrentManager).AddInfoHash(0xc4203262a0, 0xd21c8c2219ad4531, 0x1c6cf2724e3151d0, 0x27f7be7, 0xf4240)
        /mine2/CortexTheseus-1.6.0/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/torrentfs/torrentClient.go:490 +0x68b
github.com/CortexFoundation/CortexTheseus/torrentfs.(*TorrentManager).mainLoop(0xc4203262a0)
        /mine2/CortexTheseus-1.6.0/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/torrentfs/torrentClient.go:622 +0x349
created by github.com/CortexFoundation/CortexTheseus/torrentfs.(*TorrentManager).Start
        /mine2/CortexTheseus-1.6.0/build/_workspace/src/github.com/CortexFoundation/CortexTheseus/torrentfs/torrentClient.go:600 +0x63
```

**Comment by anacrolix** [comment]
What version of `torrent` are you using?

**Comment by AlexSpain** [comment]
Error while create torrent client        err="subsequent listen: listen tcp6 :33113: socket: address family not supported by protocol"
Also I noticed 

Can I use torrent without IPv6??

**Comment by AlexSpain** [comment]
How I can see version?

**Comment by anacrolix** [comment]
> Error while create torrent client err="subsequent listen: listen tcp6 :33113: socket: address family not supported by protocol"

Is this an error you previously didn't check that lead to the panic? Does handling this error now prevent the panic?

> Also I noticed
> 
> Can I use torrent without IPv6??

Yes, set DisableIPv6 in the ClientConfig.

**Comment by anacrolix** [comment]
> How I can see version?
> https://github.com/CortexFoundation/CortexTheseus/tree/3786efd5c5f29dfff584d4fe987982cacc2ae794/torrentfs

https://github.com/CortexFoundation/CortexTheseus/blob/3786efd5c5f29dfff584d4fe987982cacc2ae794/go.mod#L11

**Comment by anacrolix** [comment]
It looks like your `*Client` is `nil`. Unfortunately you have to check for errors manually in Go.

**Comment by AlexSpain** [comment]
Thank you. I update go.mod to last version and add DisableIPv6 = true to config.

Thank you for your fast help.

Very appreciated.
