### ISSUE TITLE
crash at reading piece range on certain torrent

### ISSUE THREAD

**Issue by boypt** [anacrolix/torrent#387]
Found a torrent that crashes the library:
```
magnet:?xt=urn:btih:30932B4ECCB2A09A180813509CD489752BA177AD
```

### Crash Log:

```
...(the `unexpected EOF` repeated 2000 lines )
....
2020-03-22 19:54:07 torrent.go:1688: "海洋奇缘.Moana.2016.BD1080P.X264.DTS-HD.MA.7.1.Mandarin&Taiwanese&Cantonese&English.CHS-ENG.Mp4Ba": piece 30932b4eccb2a09a180813509cd489752ba177ad/2575 (937ef5ce86ac535c65958cd353d72c18b06a1f4d) hash failure copy error: unexpected EOF
2020-03-22 19:54:07 torrent.go:1688: "海洋奇缘.Moana.2016.BD1080P.X264.DTS-HD.MA.7.1.Mandarin&Taiwanese&Cantonese&English.CHS-ENG.Mp4Ba": piece 30932b4eccb2a09a180813509cd489752ba177ad/2576 (97d253388ecc18a5ab55aac0210de4131a8f83cb) hash failure copy error: unexpected EOF
panic: rangeEnd-1 > MaxUint32

goroutine 48 [running]:
github.com/RoaringBitmap/roaring.Flip(0xc00023a000, 0x1, 0xffffffffffffffff, 0xc00123ea90)
	/home/ubuntu/go/pkg/mod/github.com/!roaring!bitmap/roaring@v0.4.21/roaring.go:1376 +0xd83
github.com/RoaringBitmap/roaring.FlipInt(...)
	/home/ubuntu/go/pkg/mod/github.com/!roaring!bitmap/roaring@v0.4.21/roaring.go:1450
github.com/anacrolix/missinggo/v2/bitmap.Flip(0xc00023a000, 0x1, 0xffffffffffffffff, 0xd0)
	/home/ubuntu/go/pkg/mod/github.com/anacrolix/missinggo/v2@v2.3.2-0.20200110051601-fc3212fb3984/bitmap/global.go:13 +0x47
github.com/anacrolix/torrent.(*File).bytesLeft(0xc0001c4af0, 0x0)
	/home/ubuntu/go/pkg/mod/github.com/anacrolix/torrent@v1.14.0/file.go:61 +0x83
github.com/anacrolix/torrent.(*File).bytesCompleted(...)
	/home/ubuntu/go/pkg/mod/github.com/anacrolix/torrent@v1.14.0/file.go:54
github.com/anacrolix/torrent.(*File).BytesCompleted(0xc0001c4af0, 0x0)
	/home/ubuntu/go/pkg/mod/github.com/anacrolix/torrent@v1.14.0/file.go:50 +0x8a


....(call to BytesCompleted causes the crash)
```

### Analyzation
The torrent is successfully downloaded from DHT, and call to `AddTorrentSpec` successfully started the torrent. But then the call to `BytesCompleted` on the torrents's file causes this crash.

 `torrent.File.BytesCompleted`  was introduced at PR #347 , maybe there's some unhandled exceptions  in the `bytesLeft()` function.

**Comment by anacrolix** [comment]
What GOARCH/GOOS is this on?

**Comment by snowie2000** [comment]
Linux for sure. Bug reproduced on linux amd64.

**Comment by boypt** [comment]
@anacrolix Sorry I didn't provide enough info at first. I updated the issue.
I believe it's related to PR #347

**Comment by anacrolix** [comment]
@boypt thanks for all the info. I wasn't able to obtain the linked torrent, but I believe it was some bad edge cases that should now be fixed.

**Comment by boypt** [comment]
fix confirmed. thanks!
