### ISSUE TITLE
panic: -1 on Torrent.pendingRequests when dropping a connection

### ISSUE THREAD

**Issue by myleshorton** [anacrolix/torrent#388]
```
2020-03-25 11:04:15 server.go:313: added metainfo for "f4b78172-1e6f-439b-a2f1-6227c5a804a2/The Genome Sequence of the SARS-Associated Coronavirus.pdf" from s3
panic: -1
	panic: -1

goroutine 10272 [running]:
github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent.(*PeerConn).deleteRequest(0xc00645f880, 0x1c00000000000, 0xc000004000, 0xc000112720)
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent/peerconn.go:1391 +0x374
github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent.(*PeerConn).deleteAllRequests(0xc00645f880)
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent/peerconn.go:1404 +0xa3
github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent.(*Torrent).deleteConnection(0xc005954700, 0xc00645f880, 0x0)
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent/torrent.go:1204 +0xc9
github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent.(*Torrent).dropConnection(0xc005954700, 0xc00645f880)
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent/torrent.go:1223 +0x5e
panic(0x4d0dca0, 0xc006f0ee08)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent.(*PeerConn).deleteRequest(0xc00645f880, 0x2000000000000, 0xc000004000, 0xc0069141b8)
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent/peerconn.go:1391 +0x374
github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent.(*PeerConn).receiveChunk(0xc00645f880, 0xc001b9a230, 0x5, 0x1)
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent/peerconn.go:1196 +0x198
github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent.(*PeerConn).mainReadLoop(0xc00645f880, 0x0, 0x0)
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent/peerconn.go:1039 +0x49c
github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent.(*Client).runHandshookConn(0xc00032a600, 0xc00645f880, 0xc005954700)
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent/client.go:880 +0x569
github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent.(*Client).outgoingConnection(0xc00032a600, 0xc005954700, 0x52cc4c0, 0xc00683f420, 0x4f07964, 0x2, 0x0)
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent/client.go:711 +0x2f4
created by github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent.(*Torrent).initiateConn
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent/torrent.go:1752 +0x1f2

goroutine 1 [syscall, 1 minutes, locked to thread]:
github.com/getlantern/flashlight/vendor/github.com/getlantern/systray._Cfunc_nativeLoop(0x7c00a70, 0x0, 0x0)
	_cgo_gotypes.go:109 +0x4d
github.com/getlantern/flashlight/vendor/github.com/getlantern/systray.nativeLoop(0x0, 0x0, 0x0, 0x0)
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/vendor/github.com/getlantern/systray/systray_nonwindows.go:20 +0x55
github.com/getlantern/flashlight/vendor/github.com/getlantern/systray.RunWithAppWindow(0x0, 0x0, 0x0, 0x0, 0xc0005593d0, 0xc000450820)
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/vendor/github.com/getlantern/systray/systray.go:85 +0xa9
github.com/getlantern/flashlight/vendor/github.com/getlantern/systray.Run(...)
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/vendor/github.com/getlantern/systray/systray.go:56
main.runOnSystrayReady(0x4dcc300, 0x52e6040, 0xc000128080, 0xc0005593d0)
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/main/systray.go:58 +0x100
main.main()
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/main/main.go:153 +0x358

goroutine 7 [syscall, 1 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:144 +0x96
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41
```

**Comment by anacrolix** [comment]
It appears at present that `Torrent.pendingRequests` is only used as a sanity check. It's previous use by one of the download strategies has been moved exclusively into those/that strategy (if it's even around anymore).

**Comment by myleshorton** [comment]
Another log -- I think it's the same but in case it's helpful:

```
panic: -1
	panic: -1

goroutine 29187 [running]:
github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent.(*PeerConn).deleteRequest(0xc007a2c700, 0xc00000000018, 0xc000004000, 0xc00009aae0)
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent/peerconn.go:1391 +0x374
github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent.(*PeerConn).deleteAllRequests(0xc007a2c700)
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent/peerconn.go:1404 +0xa3
github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent.(*Torrent).deleteConnection(0xc0000aee00, 0xc007a2c700, 0x0)
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent/torrent.go:1204 +0xc9
github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent.(*Torrent).dropConnection(0xc0000aee00, 0xc007a2c700)
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent/torrent.go:1223 +0x5e
panic(0x4d0e220, 0xc004b31cd0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent.(*PeerConn).deleteRequest(0xc007a2c700, 0x1800000000016, 0xc000004000, 0xc00890a8b8)
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent/peerconn.go:1391 +0x374
github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent.(*PeerConn).receiveChunk(0xc007a2c700, 0xc004be21c0, 0x5, 0x1)
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent/peerconn.go:1196 +0x198
github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent.(*PeerConn).mainReadLoop(0xc007a2c700, 0x0, 0x0)
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent/peerconn.go:1039 +0x49c
github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent.(*Client).runHandshookConn(0xc004877200, 0xc007a2c700, 0xc0000aee00)
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent/client.go:880 +0x569
github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent.(*Client).outgoingConnection(0xc004877200, 0xc0000aee00, 0x52cc940, 0xc0010f72e0, 0x4f07ce4, 0x2, 0x0)
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent/client.go:711 +0x2f4
created by github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent.(*Torrent).initiateConn
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent/torrent.go:1752 +0x1f2

goroutine 1 [syscall, 5 minutes, locked to thread]:
github.com/getlantern/flashlight/vendor/github.com/getlantern/systray._Cfunc_nativeLoop(0x9800f60, 0x0, 0x0)
	_cgo_gotypes.go:109 +0x4d
github.com/getlantern/flashlight/vendor/github.com/getlantern/systray.nativeLoop(0x0, 0x0, 0x0, 0x0)
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/vendor/github.com/getlantern/systray/systray_nonwindows.go:20 +0x55
github.com/getlantern/flashlight/vendor/github.com/getlantern/systray.RunWithAppWindow(0x0, 0x0, 0x0, 0x0, 0xc00044b3e0, 0xc00043c8c0)
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/vendor/github.com/getlantern/systray/systray.go:85 +0xa9
github.com/getlantern/flashlight/vendor/github.com/getlantern/systray.Run(...)
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/vendor/github.com/getlantern/systray/systray.go:56
main.runOnSystrayReady(0x4dcc700, 0x52e64c0, 0xc000120100, 0xc00044b3e0)
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/main/systray.go:58 +0x100
main.main()
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/main/main.go:153 +0x358
```

**Comment by hwh33** [comment]
Here's another crash in case it's helpful:

```
Apr 23 23:44:26.623 - 2m17s DEBUG flashlight.ui: server.go:144 changing path from "/d54cfaf557222b7e68d38d1d531121d6/replica/download" to "/replica/download"
2020-04-23 17:44:26 server.go:134: replica server request path: "/download"
Apr 23 23:44:27.967 - 2m19s DEBUG chained: persist.go:206 Saved proxy stats to /Users/harryharpham/Library/Application Support/Lantern/proxystats.csv
Apr 23 23:44:28.891 - 2m20s DEBUG balancer: balancer.go:604 ----------- Dialer Stats (2m15.95835914s) ----------- [op=client_started root_op=client_started startup_time=0.081510957]
Apr 23 23:44:28.892 - 2m20s DEBUG balancer: balancer.go:612 fp-donyc3u16-20200411-067              at     167.71.251.26:443 (t)  P:  6  R:  0  A:   71(   71)  S:   71(   71)  CS:  72  F:    0(    0)  CF:   0  R: 1.000  L:  127ms  B:  20.97Mbps  T:  116 kB/ 7.4 MB  P:   0(  0kb)/  0(  0kb) [op=client_started root_op=client_started startup_time=0.081510957]
Apr 23 23:44:28.892 - 2m20s DEBUG balancer: balancer.go:636 ----------- End Dialer Stats ----------- [op=client_started root_op=client_started startup_time=0.081510957]
2020-04-23 17:44:30 server.go:324: added metainfo for "76e463cb-a72a-49d5-b8f9-cdbb7636e031/cheetas.gif" from s3
panic: -1
	panic: -1

goroutine 9376 [running]:
github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent.(*PeerConn).deleteRequest(0xc00525f180, 0x1, 0xc000004000, 0xc0002808a0)
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent/peerconn.go:1391 +0x374
github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent.(*PeerConn).deleteAllRequests(0xc00525f180)
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent/peerconn.go:1404 +0xa3
github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent.(*Torrent).deleteConnection(0xc00508ea80, 0xc00525f180, 0x0)
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent/torrent.go:1204 +0xc9
github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent.(*Torrent).dropConnection(0xc00508ea80, 0xc00525f180)
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent/torrent.go:1223 +0x5e
--

goroutine 9376 [running]:
github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent.(*PeerConn).deleteRequest(0xc00525f180, 0x1, 0xc000004000, 0xc0002808a0)
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent/peerconn.go:1391 +0x374
github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent.(*PeerConn).deleteAllRequests(0xc00525f180)
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent/peerconn.go:1404 +0xa3
github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent.(*Torrent).deleteConnection(0xc00508ea80, 0xc00525f180, 0x0)
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent/torrent.go:1204 +0xc9
github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent.(*Torrent).dropConnection(0xc00508ea80, 0xc00525f180)
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent/torrent.go:1223 +0x5e
panic(0x4e67620, 0xc0050d9388)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent.(*PeerConn).deleteRequest(0xc00525f180, 0x3c00000000000, 0xc000004000, 0xc004e29568)
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent/peerconn.go:1391 +0x374
github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent.(*PeerConn).receiveChunk(0xc00525f180, 0xc0032fa230, 0x5, 0x1)
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent/peerconn.go:1196 +0x198
github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent.(*PeerConn).mainReadLoop(0xc00525f180, 0x0, 0x0)
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent/peerconn.go:1039 +0x49c
github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent.(*Client).runHandshookConn(0xc000232300, 0xc00525f180, 0xc00508ea80)
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent/client.go:880 +0x569
github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent.(*Client).outgoingConnection(0xc000232300, 0xc00508ea80, 0x54901e0, 0xc00428eb00, 0x509cb59, 0x2, 0x0)
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent/client.go:711 +0x2f4
created by github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent.(*Torrent).initiateConn
	/Users/afisk/go/src/github.com/getlantern/lantern-build/src/github.com/getlantern/flashlight/vendor/github.com/anacrolix/torrent/torrent.go:1752 +0x1f2
```
