### ISSUE TITLE
cmd/torrent: panic in findListenerIp()

### ISSUE THREAD

**Issue by yarikk** [anacrolix/torrent#396]
Looks like `-publicIp` became mandatory for cmd/torrent. It panics without it:
```
% torrent download -downloadRate'=2Kb' -dht'=false' -debug x.torrent
…
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x460aad1]

goroutine 153 [running]:
github.com/anacrolix/torrent.(*Client).findListenerIp(0xc000180300, 0x49890c8, 0x10, 0xc00024c24c, 0x4)
	/go/src/github.com/anacrolix/torrent/client.go:1331 +0x61
github.com/anacrolix/torrent.(*Client).publicIp(0xc000180300, 0xc00024c240, 0x10, 0x10, 0xc00024c240, 0x10, 0x10)
	/go/src/github.com/anacrolix/torrent/client.go:1315 +0x6f
github.com/anacrolix/torrent.(*Client).publicAddr(0xc000180300, 0xc00024c240, 0x10, 0x10, 0x10, 0x485df20, 0x0, 0xc00024c210)
	/go/src/github.com/anacrolix/torrent/client.go:1337 +0x4d
github.com/anacrolix/torrent.(*Client).newTorrent.func1(0x0, 0x0, 0x0, 0x4a60460, 0xc0005083c0, 0x4954bec, 0x2, 0x0, 0x0)
	/go/src/github.com/anacrolix/torrent/client.go:1038 +0x82
github.com/anacrolix/torrent.(*prioritizedPeers).Add(0xc0003f81f8, 0x0, 0x0, 0x0, 0x4a60460, 0xc0005083c0, 0x4954bec, 0x2, 0x0, 0x200)
	/go/src/github.com/anacrolix/torrent/prioritized_peers.go:41 +0x73
github.com/anacrolix/torrent.(*Torrent).addPeer(0xc0003f8000, 0x0, 0x0, 0x0, 0x4a60460, 0xc0005083c0, 0x4954bec, 0x2, 0x0)
	/go/src/github.com/anacrolix/torrent/tortorrent: exit 2
rent.go:269 +0xff
github.com/anacrolix/torrent.(*Torrent).addPeers(0xc0003f8000, 0xc0001ba800, 0x9, 0x10)
	/go/src/github.com/anacrolix/torrent/torrent.go:1451 +0x107
github.com/anacrolix/torrent.(*Torrent).AddPeers(0xc0003f8000, 0xc0001ba800, 0x9, 0x10)
	/go/src/github.com/anacrolix/torrent/t.go:228 +0xa1
github.com/anacrolix/torrent.(*trackerScraper).announce(0xc000288600, 0x2, 0x0, 0x0, 0x0, 0xdf8475800, 0xbf9ddf9ab95c5b50, 0xc7b6248f, 0x4f613e0)
	/go/src/github.com/anacrolix/torrent/tracker_scraper.go:135 +0x58e
github.com/anacrolix/torrent.(*trackerScraper).Run(0xc000288600)
	/go/src/github.com/anacrolix/torrent/tracker_scraper.go:146 +0x2cc
created by github.com/anacrolix/torrent.(*Torrent).startScrapingTracker.func1
	/go/src/github.com/anacrolix/torrent/torrent.go:1352 +0x559
```

**Comment by yarikk** [comment]
With both v4+v6 addresses specified, it panics in another place:
```
2020-04-15 14:41:54 portfwd.go:17: forwarded external UDP port 0
panic: runtime error: index out of range [3] with length 0
	panic: runtime error: index out of range [3] with length 0

goroutine 83 [running]:
encoding/binary.bigEndian.Uint32(...)
	/usr/local/Cellar/go/1.13.5/libexec/src/encoding/binary/binary.go:111
github.com/anacrolix/torrent/tracker.(*udpAnnounce).Do(0xc00042a000, 0x364bcc31a6596e16, 0xf7910de99368b87f, 0x3054472da9e60ea5, 0x15b40eb2d323030, 0xce24819bb553e12, 0x0, 0xeffb875, 0x0, 0x3, ...)
	/go/src/github.com/anacrolix/torrent/tracker/udp.go:113 +0x811
github.com/anacrolix/torrent/tracker.announceUDP(0xc0005fa520, 0x20, 0x364bcc31a6596e16, 0xf7910de99368b87f, 0x3054472da9e60ea5, 0x15b40eb2d323030, 0xce24819bb553e12, 0x0, 0xeffb875, 0x0, ...)
	/go/src/github.com/anacrolix/torrent/tracker/udp.go:313 +0x1e3
github.com/anacrolix/torrent/tracker.Announce.Do(0xc0005fa520, 0x20, 0x364bcc31a6596e16, 0xf7910de99368b87f, 0x3054472da9e60ea5, 0x15b40eb2d323030, 0xce24819bb553e12, 0x0, 0xeffb875, 0x0, ...)
	/go/src/github.com/anacrolix/torrent/tracker/tracker.go:77 +0xe2
github.com/anacrolix/torrent.(*trackerScraper).announce(0xc000272180, 0xc000000003, 0x0, 0x0, 0x0, 0xdf8475800, 0xbf9de1a8b798ece8, 0x9678cc78, 0x4f613e0)
	/go/src/github.com/anacrolix/torrent/tracker_scraper.go:130 +0x44a
github.com/anacrolix/torrent.(*trackerScraper).announceStopped(0xc000272180)
	/go/src/github.com/anacrolix/torrent/tracker_scraper.go:188 +0x33
panic(0x48f8140, 0xc0005fa480)
	/usr/local/Cellar/go/1.13.5/libexec/src/runtime/panic.go:679 +0x1b2
encoding/binary.bigEndian.Uint32(...)
	/usr/local/Cellar/go/1.13.5/libexec/src/encoding/binary/binary.go:111
github.com/anacrolix/torrent/tracker.(*udpAnnounce).Do(0xc000376000, 0x364bcc31a6596e16, 0xf7910de99368b87f, 0x3054472da9e60ea5, 0x15b40eb2d323030, 0xce24819bb553e12, 0x0, 0xeffb875, 0x0, 0x2, ...)
	/go/src/github.com/anacrolix/torrent/tracker/udp.go:113 +0x811
github.com/anacrolix/torrent/tracker.announceUDP(0xc00022e060, 0x20, 0x364bcc31a6596e16, 0xf7910de99368b87f, 0x3054472da9e60ea5, 0x15b40eb2d323030, 0xce24819bb553e12, 0x0, 0xeffb875, 0x0, ...)
	/go/src/github.com/anacrolix/torrent/tracker/udp.go:313 +0x1e3
github.com/anacrolix/torrent/tracker.Announce.Do(0xc00022e060, 0x20, 0x364bcc31a6596e16, 0xf7910de99368b87f, 0x3054472da9e60ea5, 0x15b40eb2d323030, 0xce24819bb553e12, 0x0, 0xeffb875, 0x0, ...)
	/go/src/github.com/anacrolix/torrent/tracker/tracker.go:77 +0xe2
github.com/anacrolix/torrent.(*trackerScraper).announce(0xc000272180, 0x2, 0x0, 0x0, 0x0, 0xdf8475800, 0xbf9de1a8b48c0e90, 0x936bed8f, 0x4f613e0)
	/go/src/github.com/anacrolix/torrent/tracker_scraper.go:130 +0x44a
github.com/anacrolix/torrent.(*trackerScraper).Run(0xc000272180)
	/go/src/github.com/anacrolix/torrent/tracker_scraper.go:146 +0x2cc
created by github.com/anacrolix/torrent.(*Torrent).startScrapingTracker.func1
	/go/src/github.com/anacrolix/torrent/torrent.go:1352 +0x559
=
```
Looks like port needs to be exclicitly specified too…

**Comment by backkem** [comment]
Looks like you now have to explicitly enable TCP and UDP peers using the `-tcpPeers` and `-utpPeers` flags.
