### ISSUE TITLE
Occasional crash

### ISSUE THREAD

**Issue by ccampbell** [anacrolix/torrent#419]
Hi. I am not entirely sure what causes this, but I have seen it from time to time, and it appears to be intermittent. I have not really dug into it cause I can’t consistently reproduce it, but I figured I would put it here to see if you had any ideas.

```
panic: (torrent.request) (0x4887e80,0xc077299eb0)

goroutine 696299 [running]:
github.com/anacrolix/torrent.(*peer).decExpectedChunkReceive(...)
	/torrent/peerconn.go:1174
github.com/anacrolix/torrent.(*peer).remoteRejectedRequest(0xc0246dc800, 0x100000000000000d, 0xd100000)
	/torrent/peerconn.go:1164 +0x190
github.com/anacrolix/torrent.(*PeerConn).mainReadLoop(0xc0246dc800, 0x0, 0x0)
	/torrent/peerconn.go:1145 +0xdc0
github.com/anacrolix/torrent.(*Client).runHandshookConn(0xc00021bc00, 0xc0246dc800, 0xc000240400, 0x0, 0x0)
	/torrent/client.go:929 +0x3fa
github.com/anacrolix/torrent.(*Torrent).logRunHandshookConn(0xc000240400, 0xc0246dc800, 0xc00b841100, 0x1, 0x4910868, 0x5)
	/torrent/torrent.go:1340 +0x42
github.com/anacrolix/torrent.(*Torrent).runHandshookConnLoggingErr(0xc000240400, 0xc0246dc800)
	/torrent/torrent.go:1347 +0x5e
github.com/anacrolix/torrent.(*Client).outgoingConnection(0xc00021bc00, 0xc000240400, 0x4a16880, 0xc019e80080, 0x490fbd3, 0x1, 0x0)
	/torrent/client.go:758 +0x30f
created by github.com/anacrolix/torrent.(*Torrent).initiateConn
	/torrent/torrent.go:1901 +0x1f2
```

Thanks.

**Comment by anacrolix** [comment]
Are you running torrent@master? I think this was fixed a few months ago.

**Comment by ccampbell** [comment]
Yeah, latest commit is dd906f8fa72e57adec3ad1a071fec29a55891895. I will do a `go build -a` just to be sure. Feel free to close if you want. I can reopen if I run into it again

**Comment by anacrolix** [comment]
Thanks. Let's leave it open for a while, in case someone else encounters it.

**Comment by gaozhitw** [comment]
Same problem, use the latest master.

```
panic: (torrent.request) (0xedb780,0xc02b926fb0)

goroutine 11702913 [running]:
github.com/anacrolix/torrent.(*peer).decExpectedChunkReceive(...)
	/go/pkg/mod/github.com/anacrolix/torrent@v1.15.1-0.20200811014312-e992bb78b9df/peerconn.go:1174
github.com/anacrolix/torrent.(*peer).remoteRejectedRequest(0xc011328000, 0x4b0000000000bc, 0x4000)
	/go/pkg/mod/github.com/anacrolix/torrent@v1.15.1-0.20200811014312-e992bb78b9df/peerconn.go:1164 +0x190
github.com/anacrolix/torrent.(*PeerConn).mainReadLoop(0xc011328000, 0x0, 0x0)
	/go/pkg/mod/github.com/anacrolix/torrent@v1.15.1-0.20200811014312-e992bb78b9df/peerconn.go:1145 +0xdc0
github.com/anacrolix/torrent.(*Client).runHandshookConn(0xc000506000, 0xc011328000, 0xc01257cc00, 0x0, 0x0)
	/go/pkg/mod/github.com/anacrolix/torrent@v1.15.1-0.20200811014312-e992bb78b9df/client.go:929 +0x3fa
github.com/anacrolix/torrent.(*Torrent).logRunHandshookConn(0xc01257cc00, 0xc011328000, 0x114f600, 0x1, 0xfb441f, 0x5)
	/go/pkg/mod/github.com/anacrolix/torrent@v1.15.1-0.20200811014312-e992bb78b9df/torrent.go:1340 +0x42
github.com/anacrolix/torrent.(*Torrent).runHandshookConnLoggingErr(0xc01257cc00, 0xc011328000)
	/go/pkg/mod/github.com/anacrolix/torrent@v1.15.1-0.20200811014312-e992bb78b9df/torrent.go:1347 +0x5e
github.com/anacrolix/torrent.(*Client).runReceivedConn(0xc000506000, 0xc011328000)
	/go/pkg/mod/github.com/anacrolix/torrent@v1.15.1-0.20200811014312-e992bb78b9df/client.go:899 +0xa02
github.com/anacrolix/torrent.(*Client).incomingConnection(0xc000506000, 0x11720e0, 0xc00069cd30)
	/go/pkg/mod/github.com/anacrolix/torrent@v1.15.1-0.20200811014312-e992bb78b9df/client.go:510 +0x1aa
created by github.com/anacrolix/torrent.(*Client).acceptConnections.func1
	/go/pkg/mod/github.com/anacrolix/torrent@v1.15.1-0.20200811014312-e992bb78b9df/client.go:484 +0xa8e
```

**Comment by ccampbell** [comment]
Just had this happen again as well :confused:

**Comment by anacrolix** [comment]
It looks like there's no guard on receiving piece reject messages from peers for pieces that we're already not expecting (other clients may send a chunk, then reject it, or reject stuff arbitrarily, and this would cause a panic).

**Comment by anacrolix** [comment]
Let me know if this doesn't fix the issue.
