### ISSUE TITLE
go routine panic on git build

### ISSUE THREAD

**Issue by tsynik** [anacrolix/torrent#430]
Hi. I'm using torrent in [TorrServer](https://github.com/tsynik/TorrServer/) project, and have this issue with latest git code on linux build for arm with go version go1.15.3:

```
2020-11-02T22:32:33+0000 WARN  peerconn.go:1436: connection 0x5eb4280: sending chunk to peer: unexpected EOF
panic: io.Copy will get stuck

goroutine 7922 [running]:
github.com/anacrolix/torrent/storage.Piece.ReadAt(0x87ac00, 0x2a1a300, 0x2dd4480, 0x2, 0x5866000, 0x4000, 0x4000, 0x0, 0x0, 0x76108, ...)
	/Users/nikk/go/src/TorrServer/src/github.com/anacrolix/torrent/storage/wrappers.go:76 +0x31c
github.com/anacrolix/torrent.(*Torrent).readAt(0x2880900, 0x5866000, 0x4000, 0x4000, 0x800000, 0x0, 0x58684fb5, 0x5222, 0x7acbb72c)
	/Users/nikk/go/src/TorrServer/src/github.com/anacrolix/torrent/torrent.go:1154 +0x180
github.com/anacrolix/torrent.(*PeerConn).sendChunk(0x5eb4280, 0x2, 0x0, 0x4000, 0x2eabec8, 0xc2cce8, 0x4000, 0xffffffff)
	/Users/nikk/go/src/TorrServer/src/github.com/anacrolix/torrent/peerconn.go:1553 +0x88
github.com/anacrolix/torrent.(*PeerConn).upload(0x5eb4280, 0x2eabec8, 0x5dd101)
	/Users/nikk/go/src/TorrServer/src/github.com/anacrolix/torrent/peerconn.go:1434 +0x174
github.com/anacrolix/torrent.(*PeerConn).fillWriteBuffer(0x5eb4280)
	/Users/nikk/go/src/TorrServer/src/github.com/anacrolix/torrent/peerconn.go:625 +0x68
github.com/anacrolix/torrent.(*PeerConn).writer(0x5eb4280, 0xf8475800, 0xd)
	/Users/nikk/go/src/TorrServer/src/github.com/anacrolix/torrent/peerconn.go:654 +0x58c
created by github.com/anacrolix/torrent.(*Client).runHandshookConn
	/Users/nikk/go/src/TorrServer/src/github.com/anacrolix/torrent/client.go:934 +0x310
```

binary build from 17e2251

**Comment by anacrolix** [comment]
Thanks for reporting this!

**Comment by tsynik** [comment]
And, maybe that's somehow related, but this was found from http error logging too:
```
{
"time":"2020-11-02T00:31:13.542285757Z",
"level":"-",
"prefix":"echo",
"file":"recover.go",
"line":"92",
"message":
"[PANIC RECOVER] io.Copy will get stuck goroutine 1423953 [running]:
github.com/labstack/echo/middleware.RecoverWithConfig.func1.1.1(0x7cbfc0, 0x1000, 0x0, 0x87ebc0, 0x4a1a120)
	/Users/nikk/go/src/TorrServer/src/github.com/labstack/echo/middleware/recover.go:77 +0xa8
panic(0x6d05f0, 0x8663e0)
	/usr/local/Cellar/go/1.15.3/libexec/src/runtime/panic.go:969 +0x158
github.com/anacrolix/torrent/storage.Piece.ReadAt(0x87abd8, 0x746d0e0, 0x57f6c80, 0x1, 0x1df6000, 0x8000, 0x8000, 0x0, 0x0, 0x0, ...)
	/Users/nikk/go/src/TorrServer/src/github.com/anacrolix/torrent/storage/wrappers.go:76 +0x31c
github.com/anacrolix/torrent.(*Torrent).readAt(0x4e5eb40, 0x1df6000, 0x8000, 0x8000, 0x400000, 0x0, 0x0, 0x8000, 0x0)
	/Users/nikk/go/src/TorrServer/src/github.com/anacrolix/torrent/torrent.go:1154 +0x180
github.com/anacrolix/torrent.(*reader).readOnceAt(0xb644900, 0x1df6000, 0x8000, 0x8000, 0x400000, 0x0, 0x91965b8, 0x8000, 0x0, 0x0)
	/Users/nikk/go/src/TorrServer/src/github.com/anacrolix/torrent/reader.go:220 +0x254
github.com/anacrolix/torrent.(*reader).ReadContext(0xb644900, 0x8798e8, 0x150a000, 0x1df6000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/Users/nikk/go/src/TorrServer/src/github.com/anacrolix/torrent/reader.go:149 +0xf8
github.com/anacrolix/torrent.(*reader).Read(0xb644900, 0x1df6000, 0x8000, 0x8000, 0x8000, 0x8000, 0x8000)
	/Users/nikk/go/src/TorrServer/src/github.com/anacrolix/torrent/reader.go:125 +0x48
server/torr/reader.(*Reader).Read(0x94f89a0, 0x1df6000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
	/Users/nikk/go/src/TorrServer/src/server/torr/reader/Reader.go:37 +0x40
io.(*LimitedReader).Read(0x4d68680, 0x1df6000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
	/usr/local/Cellar/go/1.15.3/libexec/src/io/io.go:455 +0xc0
io.copyBuffer(0x872e88, 0xa969d00, 0x8734a0, 0x4d68680, 0x1df6000, 0x8000, 0x8000, 0x6ec378, 0x7528d0, 0x0, ...)
	/usr/local/Cellar/go/1.15.3/libexec/src/io/io.go:409 +0xd8
io.Copy(...)
	/usr/local/Cellar/go/1.15.3/libexec/src/io/io.go:368
io.CopyN(0x872e88, 0xa969d00, 0x9548eed0, 0x94f89a0, 0xdf9144d2, 0x0, 0x1d, 0x0, 0x0, 0x5340200)
	/usr/local/Cellar/go/1.15.3/libexec/src/io/io.go:344 +0x84
net/http.serveContent(0x878388, 0xa969d00, 0x7ac7200, 0x64ccf00, 0x33, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.15.3/libexec/src/net/http/fs.go:300 +0x210
net/http.ServeContent(0x878388, 0xa969d00, 0x7ac7200, 0x64ccf00, 0x33, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.15.3/libexec/src/net/http/fs.go:167 +0x88
server/torr.(*BTServer).View(0x1518960, 0x5254d20, 0x57f6cc0, 0x87ebc0, 0x4a1a120, 0xe453c16c, 0x5254d20)
	/Users/nikk/go/src/TorrServer/src/server/torr/Play.go:26 +0x4e8
server/web.torrentView(0x87ebc0, 0x4a1a120, 0x0, 0x0)
	/Users/nikk/go/src/TorrServer/src/server/web/Torrent.go:596 +0x520
github.com/labstack/echo.(*Echo).add.func1(0x87ebc0, 0x4a1a120, 0x79fa8d, 0x1b)
	/Users/nikk/go/src/TorrServer/src/github.com/labstack/echo/echo.go:522 +0x50
server/web.ServerHeaderSet.func1(0x87ebc0, 0x4a1a120, 0x64ba00, 0x20)
	/Users/nikk/go/src/TorrServer/src/server/web/Server.go:121 +0x100
github.com/labstack/echo/middleware.RecoverWithConfig.func1.1(0x87ebc0, 0x4a1a120, 0x0, 0x0)
	/Users/nikk/go/src/TorrServer/src/github.com/labstack/echo/middleware/recover.go:98 +0xec
github.com/labstack/echo.(*Echo).ServeHTTP(0x1528b40, 0x878be8, 0xa07d5e0, 0x7ac7200)
	/Users/nikk/go/src/TorrServer/src/github.com/labstack/echo/echo.go:632 +0x138
net/http.serverHandler.ServeHTTP(0x151cfc0, 0x878be8, 0xa07d5e0, 0x7ac7200)
	/usr/local/Cellar/go/1.15.3/libexec/src/net/http/server.go:2843 +0x88
net/http.(*conn).serve(0x52cd560, 0x8798c8, 0x94f87a0)
	/usr/local/Cellar/go/1.15.3/libexec/src/net/http/server.go:1925 +0x7d0
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.15.3/libexec/src/net/http/server.go:2969 +0x2d0

goroutine 1 [semacquire, 88 minutes]:
sync.runtime_SemacquireMutex(0xc3ef44, 0x500, 0x1)
	/usr/local/Cellar/go/1.15.3/libexec/src/runtime/sema.go:71 +0x34
sync.(*Mutex).lockSlow(0xc3ef40)
	/usr/local/Cellar/go/1.15.3/libexec/src/sync/mutex.go:138 +0x1f8
sync.(*Mutex).Lock(0xc3ef40)
	/usr/local/Cellar/go/1.15.3/libexec/src/sync/mutex.go:81 +0x4c
server/web.Wait(0x152"}

2020/11/02 00:31:13 Web server error: io.Copy will get stuck /torrent/view/8f49d23d770be4b15cab1d559da27cf16cc153e4/XXX.mkv
```

**Comment by anacrolix** [comment]
I believe the error may actually be in the memcache PieceImpl.ReadAt implementation here: https://github.com/tsynik/TorrServer/blob/06d9a364d196095aa6a29e916aa31735a0862a6e/src/server/torr/storage/memcache/Piece.go#L49-L72. The panic you're encountering is a protection against a bad implementation. It will probably be enough to correctly return io.EOF if the piece buffer is exhausted somewhere.

**Comment by tsynik** [comment]
> I believe the error may actually be in the memcache PieceImpl.ReadAt implementation here: https://github.com/tsynik/TorrServer/blob/06d9a364d196095aa6a29e916aa31735a0862a6e/src/server/torr/storage/memcache/Piece.go#L49-L72. The panic you're encountering is a protection against a bad implementation. It will probably be enough to correctly return io.EOF if the piece buffer is exhausted somewhere.

Thanks for this, looks like return n, io.EOF after go p.cache.cleanPieces() on L69 eliminate this issue. I dunno is this correct way to return but it probably works now ;-)
