### ISSUE TITLE
panic on torrent v1.29.1

### ISSUE THREAD

**Issue by tsynik** [anacrolix/torrent#532]
Hi, I have this error with latest torrent release v1.29.1 in TorrServer build on armv7:

2021/07/18 09:11:27 Start web 8090
panic: unaligned 64-bit atomic operation

goroutine 419 [running]:
runtime/internal/atomic.panicUnaligned()
	/usr/local/Cellar/go/1.16.4/libexec/src/runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Xadd64(0x33404f4, 0x1, 0x0, 0x393a3444, 0x36323a38)
	/usr/local/Cellar/go/1.16.4/libexec/src/runtime/internal/atomic/asm_arm.s:233 +0x14
github.com/anacrolix/dht/v2.(*traversal).wrapQuery(0x33404b4, 0x80571c, 0x331b0e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/nikk/go/pkg/mod/github.com/anacrolix/dht/v2@v2.9.1/traversal.go:115 +0x44
github.com/anacrolix/dht/v2.(*traversal).run.func1.1(0x327e950)
	/Users/nikk/go/pkg/mod/github.com/anacrolix/dht/v2@v2.9.1/traversal.go:156 +0x30
github.com/anacrolix/dht/v2.(*traversal).beginQuery.func1.1(0x0)
	/Users/nikk/go/pkg/mod/github.com/anacrolix/dht/v2@v2.9.1/traversal.go:179 +0x98
github.com/anacrolix/dht/v2.(*Server).beginQuery.func1.1()
	/Users/nikk/go/pkg/mod/github.com/anacrolix/dht/v2@v2.9.1/server.go:745 +0x24
created by github.com/anacrolix/dht/v2.(*traversal).run
	/Users/nikk/go/pkg/mod/github.com/anacrolix/dht/v2@v2.9.1/traversal.go:164 +0x88

**Comment by tsynik** [comment]
the same with go 1.16.5

**Comment by tsynik** [comment]
This doesn't happen with dht v2.10.0, so probably will be fixed later with go.mod update. Thanks!
