### ISSUE TITLE
issue after go get -u ./...

### ISSUE THREAD

**Issue by ucwong** [anacrolix/torrent#560]
```
panic: internal error: can't find reason for requirement on github.com/kr/pretty@v0.2.1

goroutine 1 [running]:
cmd/go/internal/modget.(*resolver).updateBuildList.func1({{0xc0005e6180, 0xc000408210}, {0xc00009cf00, 0xc0007fc240}})
	/usr/local/go/src/cmd/go/internal/modget/get.go:1794 +0x10a
cmd/go/internal/modget.(*resolver).updateBuildList(0xc00084dc00, {0xa6f460, 0xc00009c000}, {0x0, 0x0, 0x0})
	/usr/local/go/src/cmd/go/internal/modget/get.go:1799 +0x5bb
cmd/go/internal/modget.(*resolver).resolveQueries(0xc00084dc00, {0xa6f460, 0xc00009c000}, {0xc0000aa040, 0x1, 0x7f72e0087fb8})
	/usr/local/go/src/cmd/go/internal/modget/get.go:1278 +0x1e5
cmd/go/internal/modget.runGet({0xa6f460, 0xc00009c000}, 0xc0000c6498, {0xc000096170, 0x1, 0x1})
	/usr/local/go/src/cmd/go/internal/modget/get.go:300 +0x374
main.invoke(0xd7ebe0, {0xc000096160, 0x2, 0x2})
	/usr/local/go/src/cmd/go/main.go:216 +0x2f6
main.main()
	/usr/local/go/src/cmd/go/main.go:173 +0x78e
```

**Comment by anacrolix** [comment]
What revision or version of anacrolix/torrent are you on? What version of Go? Thanks.

**Comment by ucwong** [comment]
It is OK before this https://github.com/anacrolix/torrent/commit/30e8d1ae7439dedc65f1df3f0a6ac15c0872a88f

**Comment by anacrolix** [comment]
I don't get this error. Maybe it's something to do with different build flags. Are you doing this from another project? What GOOS/GOARCH/CGO_ENABLED do you have? Maybe `go env` will help.

**Comment by ucwong** [comment]
yes I am using this in go.mod

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/root/CortexTheseus/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1770248520=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by ucwong** [comment]
It seems to be some issues about golang1.17 https://github.com/golang/go/issues/47979

**Comment by anacrolix** [comment]
Thanks for following up.

**Comment by anacrolix** [comment]
Reopen if it's not fixed in Go1.17.1

**Comment by anacrolix** [comment]
See https://github.com/golang/go/issues/56494, I think this is ongoing.
