### ISSUE TITLE
sigbus after switch to 1.39.1 (from 1.38.0)

### ISSUE THREAD

**Issue by AskAlexSharov** [anacrolix/torrent#699]
Hi, using anacrolix/torrent as a library. 

Got next output:
```
unexpected fault address 0x7cd8da37df80
fatal error: fault
unexpected fault address 0x7cd8dae31f80
unexpected fault address 0x7cd8da61df80
fatal error: fault
fatal error: fault
unexpected fault address 0x7cd98d341f80
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7cd8da37df80 pc=0x499f69]

goroutine 1843049 [running]:
runtime.throw({0x1206565, 0x14a8178})
	runtime/panic.go:1198 +0x71 fp=0xc056bbba70 sp=0xc056bbba40 pc=0x4654b1
runtime.sigpanic()
	runtime/signal_unix.go:732 +0x125 fp=0xc056bbbac0 sp=0xc056bbba70 pc=0x47b6c5
runtime.memmove()
	runtime/memmove_amd64.s:350 +0x3c9 fp=0xc056bbbac8 sp=0xc056bbbac0 pc=0x499f69
github.com/anacrolix/torrent/mmap_span.copyBytes(...)
	github.com/anacrolix/torrent@v1.39.1/mmap_span/mmap_span.go:62
github.com/anacrolix/torrent/mmap_span.(*MMapSpan).locateCopy.func1(0x14a8178, {0xc05a1b70c0, 0xc056bbbb80})
	github.com/anacrolix/torrent@v1.39.1/mmap_span/mmap_span.go:69 +0xae fp=0xc056bbbb48 sp=0xc056bbbac8 pc=0x934a4e
github.com/anacrolix/torrent/segments.Index.Locate.func2(0xb08c9cfb3212f3a6, {0xc056bbbbb0, 0x465d136c301b6fa0})
	github.com/anacrolix/torrent@v1.39.1/segments/index.go:43 +0x24 fp=0xc056bbbb70 sp=0xc056bbbb48 pc=0x9337e4
github.com/anacrolix/torrent/segments.Scan(0xc056bbbbe8, {0xc052b72428, 0x0}, 0xc056bbbc10)
	github.com/anacrolix/torrent@v1.39.1/segments/segments.go:43 +0xdf fp=0xc056bbbbc8 sp=0xc056bbbb70 pc=0x933a1f
github.com/anacrolix/torrent/segments.Index.Locate({{0xc0056c4530, 0x1, 0x1}}, {0x528000, 0x4000}, 0xc052b72488)
	github.com/anacrolix/torrent@v1.39.1/segments/index.go:42 +0x190 fp=0xc056bbbc50 sp=0xc056bbbbc8 pc=0x933750
github.com/anacrolix/torrent/mmap_span.(*MMapSpan).locateCopy(0xc000d42000, 0xc01f53f7a0, {0xc00b13a000, 0x4000, 0x4000}, 0x43ab11)
	github.com/anacrolix/torrent@v1.39.1/mmap_span/mmap_span.go:66 +0xa5 fp=0xc056bbbcc0 sp=0xc056bbbc50 pc=0x934945
github.com/anacrolix/torrent/mmap_span.(*MMapSpan).ReadAt(0x8, {0xc00b13a000, 0x4000, 0xc000d42000}, 0xc025407940)
	github.com/anacrolix/torrent@v1.39.1/mmap_span/mmap_span.go:54 +0xe8 fp=0xc056bbbd40 sp=0xc056bbbcc0 pc=0x934788
io.(*SectionReader).ReadAt(0x6, {0xc00b13a000, 0xc025407948, 0x105b560}, 0xc025407940)
	io/io.go:539 +0x9f fp=0xc056bbbd78 sp=0xc056bbbd40 pc=0x4c2a9f
github.com/anacrolix/torrent/storage.(*mmapStoragePiece).ReadAt(0xc01f53f7a0, {0xc00b13a000, 0xc052b72618, 0xc04adfd360}, 0xc052b725f8)
	<autogenerated>:1 +0x35 fp=0xc056bbbdb0 sp=0xc056bbbd78 pc=0xb1b655
github.com/anacrolix/torrent/storage.Piece.ReadAt({{0x14b2618, 0xc01f53f7a0}, {0xc00095e150, 0x0}}, {0xc00b13a000, 0x4000, 0x4000}, 0x28000)
	github.com/anacrolix/torrent@v1.39.1/storage/wrappers.go:83 +0x14a fp=0xc056bbbe38 sp=0xc056bbbdb0 pc=0xb1990a
github.com/anacrolix/torrent.(*Torrent).readAt(0xc003eb2800, {0xc00b13a000, 0xc0086fe198, 0x1d89750}, 0xc052b72710)
	github.com/anacrolix/torrent@v1.39.1/torrent.go:1281 +0x14d fp=0xc056bbbec8 sp=0xc056bbbe38 pc=0xd46c0d
github.com/anacrolix/torrent.readPeerRequestData({0x678dc20, {0xc0, 0xc09d20}}, 0xc026671800)
	github.com/anacrolix/torrent@v1.39.1/peerconn.go:1021 +0x7c fp=0xc056bbbf28 sp=0xc056bbbec8 pc=0xd2df1c
github.com/anacrolix/torrent.(*PeerConn).peerRequestDataReader(0xc026671800, {0x0, {0x0, 0x678dc20}}, 0xc04475b5d8)
	github.com/anacrolix/torrent@v1.39.1/peerconn.go:979 +0x56 fp=0xc056bbbfb0 sp=0xc056bbbf28 pc=0xd2da36
github.com/anacrolix/torrent.(*PeerConn).onReadRequest·dwrap·40()
	github.com/anacrolix/torrent@v1.39.1/peerconn.go:973 +0x33 fp=0xc056bbbfe0 sp=0xc056bbbfb0 pc=0xd2d9b3
runtime.goexit()
	runtime/asm_amd64.s:1581 +0x1 fp=0xc056bbbfe8 sp=0xc056bbbfe0 pc=0x498d21
created by github.com/anacrolix/torrent.(*PeerConn).onReadRequest
	github.com/anacrolix/torrent@v1.39.1/peerconn.go:973 +0x305@77
```

**Comment by anacrolix** [comment]
Could you share the resolution? Was it user-error in this case?

**Comment by AskAlexSharov** [comment]
Error on my side. My app did re-generate files in background - but they expected to be immutable.

**Comment by anacrolix** [comment]
Thanks for following up!
