### ISSUE TITLE
Couple panics on readlimiter

### ISSUE THREAD

**Issue by AskAlexSharov** [anacrolix/torrent#729]
Here is couple panics on version v1.41.0: 

```
panic: 10 [recovered]
	panic: 10

goroutine 11484 [running]:
github.com/anacrolix/missinggo/perf.ScopeTimerErr.func1()
	github.com/anacrolix/missinggo/perf@v1.0.0/scope.go:23 +0xa5
panic({0x16c6fa0, 0x36ce270})
	runtime/panic.go:1047 +0x266
github.com/anacrolix/torrent.(*rateLimitedReader).Read(0xc00397c090, {0xc000541d4a, 0xa, 0xa})
	github.com/anacrolix/torrent@v1.41.0/ratelimitreader.go:47 +0x254
io.(*multiReader).Read(0xc002029ae8, {0xc000541d4a, 0xa, 0xa})
	io/multi.go:26 +0x9b
io.(*LimitedReader).Read(0xc002029b48, {0xc000541d4a, 0xc0021bb610, 0x487212})
	io/io.go:473 +0x45
io.ReadAtLeast({0x27da5e0, 0xc002029b48}, {0xc000541d40, 0x14, 0x14}, 0x14)
	io/io.go:328 +0x9a
io.ReadFull(...)
	io/io.go:347
github.com/anacrolix/torrent/mse.readUntil({0x27da5e0, 0xc002029b48}, {0xc000541d28, 0x14, 0xc0036dd6c0})
	github.com/anacrolix/torrent@v1.41.0/mse/mse.go:350 +0x85
github.com/anacrolix/torrent/mse.(*handshake).receiverSteps(0xc00392d200)
	github.com/anacrolix/torrent@v1.41.0/mse/mse.go:432 +0x17a
github.com/anacrolix/torrent/mse.(*handshake).Do(0xc00392d200)
	github.com/anacrolix/torrent@v1.41.0/mse/mse.go:539 +0x29b
github.com/anacrolix/torrent/mse.ReceiveHandshakeEx({0x27f0df0, 0xc0037653a0}, 0xc003232110, 0x25eafb0)
	github.com/anacrolix/torrent@v1.41.0/mse/mse.go:579 +0x117
github.com/anacrolix/torrent/mse.ReceiveHandshake(...)
	github.com/anacrolix/torrent@v1.41.0/mse/mse.go:568
github.com/anacrolix/torrent.handleEncryption({0x27f0df0, 0xc002b12fc0}, 0x3ae6cb3806255, {0x0, 0x0}, 0x25f0748)
	github.com/anacrolix/torrent@v1.41.0/handshake.go:68 +0x2ba
github.com/anacrolix/torrent.(*Client).receiveHandshakes(0xc000c50500, 0xc002356000)
	github.com/anacrolix/torrent@v1.41.0/client.go:848 +0x1a5
github.com/anacrolix/torrent.(*Client).runReceivedConn(0xc000c50500, 0xc002356000)
	github.com/anacrolix/torrent@v1.41.0/client.go:908 +0xc5
github.com/anacrolix/torrent.(*Client).incomingConnection(0xc000c50500, {0x2826ff0, 0xc00132c400})
	github.com/anacrolix/torrent@v1.41.0/client.go:556 +0x21d
created by github.com/anacrolix/torrent.(*Client).acceptConnections.func1
	github.com/anacrolix/torrent@v1.41.0/client.go:522 +0x215
exit status 2
```

```
panic: 12438

goroutine 5497 [running]:
github.com/anacrolix/torrent.(*rateLimitedReader).Read(0xc0029b1080, {0xc004522000, 0x20000, 0x20000})
	github.com/anacrolix/torrent@v1.41.0/ratelimitreader.go:47 +0x254
github.com/anacrolix/torrent.deadlineReader.Read({{0x2827010, 0xc003704500}, {0x7f395c50ef48, 0xc0001c2fa0}}, {0xc004522000, 0x20000, 0x20000})
	github.com/anacrolix/torrent@v1.41.0/handshake.go:27 +0x102
bufio.(*Reader).Read(0xc0026d23c0, {0xc006cd05bd, 0x1a43, 0x9})
	bufio/bufio.go:227 +0x1b4
io.ReadAtLeast({0x27d6080, 0xc0026d23c0}, {0xc006cce000, 0x4000, 0x4000}, 0x4000)
	io/io.go:328 +0x9a
io.ReadFull(...)
	io/io.go:347
github.com/anacrolix/torrent/peer_protocol.(*Decoder).Decode(0xc00203d710, 0xc002bd8070)
	github.com/anacrolix/torrent@v1.41.0/peer_protocol/decoder.go:75 +0x765
github.com/anacrolix/torrent.(*PeerConn).mainReadLoop.func2(0xc00183c000, 0x1676300, 0xc002376c50, 0xc00203d6d0)
	github.com/anacrolix/torrent@v1.41.0/peerconn.go:1127 +0x86
github.com/anacrolix/torrent.(*PeerConn).mainReadLoop(0xc00285f500)
	github.com/anacrolix/torrent@v1.41.0/peerconn.go:1128 +0x2b3
github.com/anacrolix/torrent.(*Client).runHandshookConn(0xc00183c000, 0xc00285f500, 0xc000544000)
	github.com/anacrolix/torrent@v1.41.0/client.go:973 +0x50f
github.com/anacrolix/torrent.(*Torrent).logRunHandshookConn(0xc000544000, 0xc000544000, 0x0, {0x12, {0x193f554, 0xc001fc0668}})
	github.com/anacrolix/torrent@v1.41.0/torrent.go:1572 +0x6a
github.com/anacrolix/torrent.(*Torrent).runHandshookConnLoggingErr(...)
	github.com/anacrolix/torrent@v1.41.0/torrent.go:1579
github.com/anacrolix/torrent.(*Client).outgoingConnection(0xc00183c000, 0x0, {0x27db340, 0xc002bf7720}, {0x193d7fc, 0x2}, 0x0)
	github.com/anacrolix/torrent@v1.41.0/client.go:776 +0x3b8
created by github.com/anacrolix/torrent.(*Torrent).initiateConn
	github.com/anacrolix/torrent@v1.41.0/torrent.go:2180 +0x265
exit status 2
```

**Comment by AskAlexSharov** [comment]
And panic on write limiter: 
```
panic: upload rate limiter burst size < 8458

goroutine 3110 [running]:
github.com/anacrolix/torrent.(*PeerConn).upload(0xc004098a80, 0xc000fa9be8)
	github.com/anacrolix/torrent@v1.41.0/peerconn.go:1568 +0x3c5
github.com/anacrolix/torrent.(*PeerConn).fillWriteBuffer(0xc004098a80)
	github.com/anacrolix/torrent@v1.41.0/peerconn.go:688 +0x8f
github.com/anacrolix/torrent.(*PeerConn).startWriter.func1()
	github.com/anacrolix/torrent@v1.41.0/peer-conn-msg-writer.go:24 +0xa6
github.com/anacrolix/torrent.(*peerConnMsgWriter).run(0xc004098ee0, 0xdf8475800)
	github.com/anacrolix/torrent@v1.41.0/peer-conn-msg-writer.go:69 +0xde
github.com/anacrolix/torrent.(*PeerConn).startWriter.func3()
	github.com/anacrolix/torrent@v1.41.0/peer-conn-msg-writer.go:40 +0xdd
created by github.com/anacrolix/torrent.(*PeerConn).startWriter
	github.com/anacrolix/torrent@v1.41.0/peer-conn-msg-writer.go:36 +0x1f1
exit status 2
```
But I set burst size: 2*16384

**Comment by AskAlexSharov** [comment]
looks like it's because I passed 0 to first argument of ratelimiter

**Comment by anacrolix** [comment]
Thanks for following up. It did seem strange, I had some some pretty significant testing of this a long while back.
