### ISSUE TITLE
panic parsing tags

### ISSUE THREAD

**Issue by stephens2424** [anacrolix/torrent#74]
A fresh install after a `go get -u` yields  a panic. I'm on Ubuntu (4.2.0-35-generic x86_64)

Here's the stack trace:

```
stephen@stephen-xps:~/go/src/github.com/anacrolix/torrent/cmd/torrent$ torrent
panic: (ctrlflow.valueWrapper) (0x8f3400,0xc82011e4d0)

goroutine 1 [running]:
panic(0x8f3400, 0xc82011e4d0)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/anacrolix/missinggo/ctrlflow.Panic(0x916920, 0xc82011e4c0)
        /home/stephen/go/src/github.com/anacrolix/missinggo/ctrlflow/ctrlflow.go:8 +0x70
github.com/anacrolix/tagflag.raiseError(0x7f3c49cfe3b0, 0xc82011e4c0)
        /home/stephen/go/src/github.com/anacrolix/tagflag/tagflag.go:434 +0x45
github.com/anacrolix/tagflag.raiseLogicError(0xc820120320, 0x4b)
        /home/stephen/go/src/github.com/anacrolix/tagflag/tagflag.go:442 +0x88
github.com/anacrolix/tagflag.(*parser).skipCannotSet(0xc820162000, 0x97d780, 0xc63120, 0x199, 0x9a6948, 0x6, 0x0, 0x0, 0x7f3c49d420a8, 0x97d780, ...)
        /home/stephen/go/src/github.com/anacrolix/tagflag/tagflag.go:283 +0x429
github.com/anacrolix/tagflag.(*parser).addFlag(0xc820162000, 0xc820162028, 0x97d780, 0xc63120, 0x199, 0x9a6948, 0x6, 0x0, 0x0, 0x7f3c49d420a8, ...)
        /home/stephen/go/src/github.com/anacrolix/tagflag/tagflag.go:288 +0x6e
github.com/anacrolix/tagflag.(*parser).addCmd.func1(0x97d780, 0xc63120, 0x199, 0x9a6948, 0x6, 0x0, 0x0, 0x7f3c49d420a8, 0x97d780, 0x9be290, ...)
        /home/stephen/go/src/github.com/anacrolix/tagflag/tagflag.go:338 +0x297
github.com/anacrolix/tagflag.foreachStructField(0x9270c0, 0xc63120, 0x199, 0xc82004fb98)
        /home/stephen/go/src/github.com/anacrolix/tagflag/tagflag.go:310 +0x1cf
github.com/anacrolix/tagflag.(*parser).addCmd(0xc820162000, 0x8087c0, 0xc63120)
        /home/stephen/go/src/github.com/anacrolix/tagflag/tagflag.go:340 +0x162
github.com/anacrolix/tagflag.newParser(0x8087c0, 0xc63120, 0xc82011af00, 0x4, 0x6, 0xc820162000)
        /home/stephen/go/src/github.com/anacrolix/tagflag/tagflag.go:702 +0x149
github.com/anacrolix/tagflag.Parse(0x8087c0, 0xc63120, 0xc82004fd60, 0x1, 0x1)
        /home/stephen/go/src/github.com/anacrolix/tagflag/tagflag.go:679 +0x2ba
main.main()
        /home/stephen/go/src/github.com/anacrolix/torrent/cmd/torrent/main.go:121 +0xee
```

**Comment by anacrolix** [comment]
Thanks, fixing now.

**Comment by anacrolix** [comment]
Should be fixed as of https://github.com/anacrolix/torrent/commit/2dcbe3130423cc287f23af4e378503cdf21cd7d2
