### ISSUE TITLE
panic on apply new options with v1.43.1

### ISSUE THREAD

**Issue by tsynik** [anacrolix/torrent#747]
```
2022/05/14 01:34:34 UTC0 SRV Client config: {"CacheSize":67108864,"ReaderReadAHead":95,"PreloadCache":100,"UseDisk":false,"TorrentsSavePath":"","RemoveCacheOnDrop":false,"ForceEncrypt":false,"RetrackersMode":1,"TorrentDisconnectTimeout":30,"EnableDebug":true,"EnableDLNA":true,"EnableIPv6":false,"DisableTCP":false,"DisableUTP":false,"DisableUPNP":false,"DisableDHT":false,"DisablePEX":false,"DisableUpload":false,"DownloadRateLimit":0,"UploadRateLimit":0,"ConnectionsLimit":25,"PeersListenPort":0}
2022/05/14 01:34:35 UTC0 SRV New torrent 1c5f6658a35d4b08f5678a92135ecbb26f3f5fe7
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7c039c]

goroutine 1778 [running]:
github.com/anacrolix/torrent.(*Client).lock(...)
	/Users/nikk/go/pkg/mod/github.com/anacrolix/torrent@v1.43.1/client.go:1645
github.com/anacrolix/torrent.(*Client).AddTorrentOpt(0x0, {{0x1c, 0x5f, 0x66, 0x58, 0xa3, 0x5d, 0x4b, 0x8, 0xf5, ...}, ...})
	/Users/nikk/go/pkg/mod/github.com/anacrolix/torrent@v1.43.1/client.go:1256 +0x50
github.com/anacrolix/torrent.(*Client).AddTorrentSpec(0x0, 0x3748180)
	/Users/nikk/go/pkg/mod/github.com/anacrolix/torrent@v1.43.1/client.go:1287 +0x74
server/torr.NewTorrent(0x3748180, 0x33263a8)
	/Users/nikk/XCode/TorrServer/server/torr/torrent.go:71 +0x3d0
server/torr.GetTorrent.func1()
	/Users/nikk/XCode/TorrServer/server/torr/apihelper.go:95 +0x100
created by server/torr.GetTorrent
	/Users/nikk/XCode/TorrServer/server/torr/apihelper.go:93 +0x154
```

**Comment by anacrolix** [comment]
@tsynik this would occur if `*Client` is `nil`, which wouldn't be an issue from this repo. Maybe it occurs during shutdown in TorrServer?

**Comment by tsynik** [comment]
> this would occur if `*Client` is `nil`, which wouldn't be an issue from this repo. Maybe it occurs during shutdown in TorrServer?
Probably yes, TorrServer drop all torrents and disconnect and connect client to apply new options. Maybe there is some race condition, so I'll close this.
