### ISSUE TITLE
Error getting repository, there is a dependency that has replaced the address

### ISSUE THREAD

**Issue by lostmaniac** [anacrolix/torrent#792]
go get github.com/anacrolix/torrent@master
go: downloading github.com/anacrolix/torrent v1.47.1-0.20221211042123-f75989863cfc
panic: internal error: can't find reason for requirement on github.com/willf/bitset@v1.1.10

goroutine 1 [running]:
cmd/go/internal/modget.(*resolver).updateBuildList.func1({{0xc0003ff6f8?, 0xc000425e90?}, {0xc000028f86?, 0xc0002df020?}})
        /usr/local/go/src/cmd/go/internal/modget/get.go:1760 +0x114
cmd/go/internal/modget.(*resolver).updateBuildList(0xc00045a300, {0xb2e5f0, 0xc000028088}, {0x0, 0x0, 0x0})
        /usr/local/go/src/cmd/go/internal/modget/get.go:1765 +0x597
cmd/go/internal/modget.(*resolver).resolveQueries(0xc00045a300, {0xb2e5f0, 0xc000028088}, {0xc000014060, 0x1, 0x472445?})
        /usr/local/go/src/cmd/go/internal/modget/get.go:1243 +0x1e5
cmd/go/internal/modget.runGet({0xb2e5f0, 0xc000028088}, 0xc0000265b8?, {0xc0000241a0, 0x1, 0x1})
        /usr/local/go/src/cmd/go/internal/modget/get.go:314 +0x40b
main.invoke(0xe28fa0, {0xc000024190, 0x2, 0x2})
        /usr/local/go/src/cmd/go/main.go:225 +0x34e
main.main()
        /usr/local/go/src/cmd/go/main.go:179 +0x7d1

---
github.com/willf/bitset has been replaced with https://github.com/bits-and-blooms/bitset

**Comment by anacrolix** [comment]
I believe this is a known issue in Go, see https://github.com/golang/go/issues/56494.

**Comment by anacrolix** [comment]
I can't reproduce this:
```
$ mkdir blah
$ cd blah/
$ go mod init issue792
go: creating new go.mod: module issue792
$ go get github.com/anacrolix/torrent@master
go: downloading github.com/anacrolix/torrent v1.48.1-0.20230130214106-5a185c45c08c
go: added crawshaw.io/sqlite v0.3.3-0.20220618202545-d1964889ea3c
go: added github.com/RoaringBitmap/roaring v1.2.3
go: added github.com/ajwerner/btree v0.0.0-20211221152037-f427b3e689c0
go: added github.com/alecthomas/atomic v0.1.0-alpha2
go: added github.com/anacrolix/chansync v0.3.0
go: added github.com/anacrolix/dht/v2 v2.19.2-0.20221121215055-066ad8494444
go: added github.com/anacrolix/envpprof v1.2.1
go: added github.com/anacrolix/generics v0.0.0-20220618083756-f99e35403a60
go: added github.com/anacrolix/go-libutp v1.2.0
go: added github.com/anacrolix/log v0.13.2-0.20221123232138-02e2764801c3
go: added github.com/anacrolix/missinggo v1.3.0
go: added github.com/anacrolix/missinggo/perf v1.0.0
go: added github.com/anacrolix/missinggo/v2 v2.7.0
go: added github.com/anacrolix/mmsg v1.0.0
go: added github.com/anacrolix/multiless v0.3.0
go: added github.com/anacrolix/stm v0.4.0
go: added github.com/anacrolix/sync v0.4.0
go: added github.com/anacrolix/torrent v1.48.1-0.20230130214106-5a185c45c08c
go: added github.com/anacrolix/upnp v0.1.3-0.20220123035249-922794e51c96
go: added github.com/anacrolix/utp v0.1.0
go: added github.com/bahlo/generic-list-go v0.2.0
go: added github.com/benbjohnson/immutable v0.3.0
go: added github.com/bits-and-blooms/bitset v1.2.2
go: added github.com/bradfitz/iter v0.0.0-20191230175014-e8f45d346db8
go: added github.com/davecgh/go-spew v1.1.1
go: added github.com/dustin/go-humanize v1.0.0
go: added github.com/edsrzf/mmap-go v1.1.0
go: added github.com/go-logr/logr v1.2.3
go: added github.com/go-logr/stdr v1.2.2
go: added github.com/google/btree v1.1.2
go: added github.com/google/uuid v1.3.0
go: added github.com/gorilla/websocket v1.5.0
go: added github.com/huandu/xstrings v1.3.2
go: added github.com/lispad/go-generics-tools v1.1.0
go: added github.com/mschoch/smat v0.2.0
go: added github.com/pion/datachannel v1.5.2
go: added github.com/pion/dtls/v2 v2.1.5
go: added github.com/pion/ice/v2 v2.2.6
go: added github.com/pion/interceptor v0.1.11
go: added github.com/pion/logging v0.2.2
go: added github.com/pion/mdns v0.0.5
go: added github.com/pion/randutil v0.1.0
go: added github.com/pion/rtcp v1.2.9
go: added github.com/pion/rtp v1.7.13
go: added github.com/pion/sctp v1.8.2
go: added github.com/pion/sdp/v3 v3.0.5
go: added github.com/pion/srtp/v2 v2.0.9
go: added github.com/pion/stun v0.3.5
go: added github.com/pion/transport v0.13.1
go: added github.com/pion/turn/v2 v2.0.8
go: added github.com/pion/udp v0.1.1
go: added github.com/pion/webrtc/v3 v3.1.42
go: added github.com/pkg/errors v0.9.1
go: added github.com/rs/dnscache v0.0.0-20211102005908-e0241e321417
go: added github.com/tidwall/btree v1.6.0
go: added go.etcd.io/bbolt v1.3.6
go: added go.opentelemetry.io/otel v1.8.0
go: added go.opentelemetry.io/otel/trace v1.8.0
go: added golang.org/x/crypto v0.0.0-20220622213112-05595931fe9d
go: added golang.org/x/exp v0.0.0-20220613132600-b0d781184e0d
go: added golang.org/x/net v0.0.0-20220630215102-69896b714898
go: added golang.org/x/sync v0.0.0-20220601150217-0de741cfad7f
go: added golang.org/x/sys v0.0.0-20220702020025-31831981b65f
go: added golang.org/x/time v0.0.0-20220609170525-579cf78fd858
```
I also tried with `GOPROXY=direct`. Please reopen if there's more information.
