### ISSUE TITLE
ratelimireader.go panic

### ISSUE THREAD

**Issue by AskAlexSharov** [anacrolix/torrent#911]
```
panic: 18

goroutine 3228 [running]:
github.com/anacrolix/torrent.(*rateLimitedReader).Read(0xc02768c420, {0xc02b580000, 0x20000, 0x20000})
	github.com/anacrolix/torrent@v1.55.0/ratelimitreader.go:47 +0x225
io.(*multiReader).Read(0xc027760a20, {0xc02b580000, 0x20000, 0x20000})
	io/multi.go:26 +0x93
io.(*multiReader).Read(0xc0278263f0, {0xc02b580000, 0x20000, 0x20000})
	io/multi.go:26 +0x93
github.com/anacrolix/torrent.deadlineReader.Read({{0x30a1a70?, 0xc025ee2100?}, {0x7f8c8c076f20?, 0xc025c91aa0?}}, {0xc02b580000, 0x20000, 0x20000})
	github.com/anacrolix/torrent@v1.55.0/handshake.go:27 +0xf1
bufio.(*Reader).Read(0xc02b2e2ae0, {0xc000ed58b4, 0x4, 0x432185?})
	bufio/bufio.go:244 +0x197
io.ReadAtLeast({0x3076880, 0xc02b2e2ae0}, {0xc000ed58b4, 0x4, 0x4}, 0x4)
	io/io.go:335 +0x90
io.ReadFull(...)
	io/io.go:354
github.com/anacrolix/torrent/peer_protocol.(*Integer).Read(0x3076880?, {0x3076880, 0xc02b2e2ae0})
	github.com/anacrolix/torrent@v1.55.0/peer_protocol/int.go:29 +0x50
github.com/anacrolix/torrent/peer_protocol.(*Decoder).Decode(0xc0216b14e0, 0xc000195e30)
	github.com/anacrolix/torrent@v1.55.0/peer_protocol/decoder.go:25 +0x65
github.com/anacrolix/torrent.(*PeerConn).mainReadLoop.func2(0xc000a3ca00, 0xc0216b14a0, 0xc000ed5860?, 0xc?)
	github.com/anacrolix/torrent@v1.55.0/peerconn.go:733 +0x7f
github.com/anacrolix/torrent.(*PeerConn).mainReadLoop(0xc025660a80)
	github.com/anacrolix/torrent@v1.55.0/peerconn.go:734 +0x2ba
github.com/anacrolix/torrent.(*Torrent).runHandshookConn(0xc025579500, 0xc025660a80)
	github.com/anacrolix/torrent@v1.55.0/client.go:1100 +0x537
github.com/anacrolix/torrent.(*Torrent).logRunHandshookConn(0xc025579500, 0x29f50d5?, 0x0, {0x0?})
	github.com/anacrolix/torrent@v1.55.0/torrent.go:1692 +0x39
github.com/anacrolix/torrent.(*Torrent).runHandshookConnLoggingErr(...)
	github.com/anacrolix/torrent@v1.55.0/torrent.go:1699
github.com/anacrolix/torrent.(*Client).runReceivedConn(0xc000a3ca00, 0xc025660a80)
	github.com/anacrolix/torrent@v1.55.0/client.go:1059 +0x185
github.com/anacrolix/torrent.(*Client).incomingConnection(0xc000a3ca00, {0x30a1a70?, 0xc025ee2100})
	github.com/anacrolix/torrent@v1.55.0/client.go:600 +0x385
created by github.com/anacrolix/torrent.(*Client).acceptConnections.func1 in goroutine 3227
	github.com/anacrolix/torrent@v1.55.0/client.go:558 +0x1f9
```

my config:
upload ratelimit: `512k`
download ratelimit: `not set`

**Comment by anacrolix** [comment]
I think it's like you don't have the download rate limiter set? That should only occur if the burst limit is too low. If you have it set to the default (unlimited download) it should allow any burst size.

**Comment by AskAlexSharov** [comment]
hmmm... yes, we don't set download rate limiter if our cli limit parameter > 512mb/s 
thank you. i will set.
