### ISSUE TITLE
Panic with latest master and golang 1.6.2

### ISSUE THREAD

**Issue by ccampbell** [anacrolix/torrent#95]
I am not 100% sure how to reproduce this, but I just ran into this:

```
panic(0xa2a320, 0xc82011a4f0)
    /usr/local/go/src/runtime/panic.go:481 +0x3e6
project/vendor/github.com/anacrolix/torrent/storage.(*dbPieceCompletion).Get(0xc820020078, 0xc82038cd90, 0x0, 0xc8200b7000)
    go/src/project/vendor/github.com/anacrolix/torrent/storage/db.go:33 +0x302
project/vendor/github.com/anacrolix/torrent/storage.(*fileStoragePiece).GetIsComplete(0xc820620c80, 0x7fd4e5119728)
    go/src/project/vendor/github.com/anacrolix/torrent/storage/file.go:65 +0x54
project/vendor/github.com/anacrolix/torrent.(*Torrent).pieceCompleteUncached(0xc824164500, 0x0, 0xffffffffffffffff)
    go/src/project/vendor/github.com/anacrolix/torrent/torrent.go:111 +0x74
project/vendor/github.com/anacrolix/torrent.(*Torrent).updatePieceCompletion(0xc824164500, 0x0)
    go/src/project/vendor/github.com/anacrolix/torrent/torrent.go:996 +0x2f
project/vendor/github.com/anacrolix/torrent.(*Torrent).setInfoBytes(0xc824164500, 0xc8202c0000, 0x4c24, 0x4c24, 0x0, 0x0)
    go/src/project/vendor/github.com/anacrolix/torrent/torrent.go:255 +0xdd3
project/vendor/github.com/anacrolix/torrent.(*Torrent).maybeMetadataCompleted(0xc824164500)
    go/src/project/vendor/github.com/anacrolix/torrent/torrent.go:1028 +0x8c
project/vendor/github.com/anacrolix/torrent.(*Client).gotMetadataExtensionMsg(0xc820131500, 0xc8240b6000, 0x402d, 0x7e00, 0xc824164500, 0xc822efd2c0, 0x0, 0x0)
    go/src/project/vendor/github.com/anacrolix/torrent/client.go:1058 +0x9dc
project/vendor/github.com/anacrolix/torrent.(*Client).connectionLoop(0xc820131500, 0xc824164500, 0xc822efd2c0, 0x0, 0x0)
    go/src/project/vendor/github.com/anacrolix/torrent/client.go:1279 +0x1f69
project/vendor/github.com/anacrolix/torrent.(*Client).runHandshookConn(0xc820131500, 0xc822efd2c0, 0xc824164500)
    go/src/project/vendor/github.com/anacrolix/torrent/client.go:945 +0x3a4
project/vendor/github.com/anacrolix/torrent.(*Client).runInitiatedHandshookConn(0xc820131500, 0xc822efd2c0, 0xc824164500)
    go/src/project/vendor/github.com/anacrolix/torrent/client.go:902 +0x14a
project/vendor/github.com/anacrolix/torrent.(*Client).outgoingConnection(0xc820131500, 0xc824164500, 0xc82034f620, 0x13, 0x48)
    go/src/project/vendor/github.com/anacrolix/torrent/client.go:648 +0x287
created by project/vendor/github.com/anacrolix/torrent.(*Client).initiateConn
    go/src/project/vendor/github.com/anacrolix/torrent/client.go:504 +0x2f9
```

Hopefully you might have some idea what could cause that

**Comment by anacrolix** [comment]
Do you have the few lines before this, that contain the error message? This should only happen if your DB has the wrong schema.

**Comment by ccampbell** [comment]
Whoops sorry yes

```
panic: sql: database is closed

goroutine 8116704 [running]:
panic(0xa2a320, 0xc82011a4f0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
```

**Comment by ccampbell** [comment]
It also was triggered right after the behavior I mentioned in #96, but not sure if that is related

**Comment by anacrolix** [comment]
Okay I think I know what it is. Do you close or drop torrents in your program? Possibly around the time this occurs?

**Comment by ccampbell** [comment]
It's possible. I have a timer running that will drop and remove any torrents that haven't been accessed in the last x minutes

**Comment by anacrolix** [comment]
I'll write a test for the storage code for this. Expect a fix in the next hour or so.

**Comment by anacrolix** [comment]
Thanks for the good catch. I've added tests for it. Hopefully this doesn't introduce anything, I'm not sure how well sqlite3 handles multiple DB connections, which is the easy fix I've opted for. It's also nicely solved a sql.DB handle leak in the core torrent package.
