### ISSUE TITLE
New crash after dropping torrent

### ISSUE THREAD

**Issue by ccampbell** [anacrolix/torrent#97]
I was just testing out the fixes to #95 and #96 and ran into this. Seemed to happen right after a torrent was dropped/removed.

```
2016/07/11 23:23:02 TORRENT_NAME: piece 145 (f6f9ec19acb09d738232756558b5d17c7c223d6c) failed hash
2016/07/11 23:23:02 dropping and banning 2 conns that touched piece
panic: sql: database is closed
	panic: sync: Unlock of unlocked RWMutex

goroutine 72146 [running]:
panic(0x45c7620, 0xc82000bc80)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
sync.(*RWMutex).Unlock(0xc820127438)
	/usr/local/Cellar/go/1.6.2/libexec/src/sync/rwmutex.go:115 +0xa3
magneto/vendor/github.com/anacrolix/sync.(*RWMutex).Unlock(0xc820127308)
	/Users/craig/go-clean/src/magneto/vendor/github.com/anacrolix/sync/rwmutex.go:26 +0x57
panic(0x46971e0, 0xc82000b780)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:443 +0x4e9
magneto/vendor/github.com/anacrolix/torrent/storage.(*dbPieceCompletion).Set(0xc820024150, 0xc82022a380, 0x84, 0x8000)
	/Users/craig/go-clean/src/magneto/vendor/github.com/anacrolix/torrent/storage/db.go:46 +0x284
magneto/vendor/github.com/anacrolix/torrent/storage.(*fileStoragePiece).ReadAt(0xc8256571c0, 0xc8205aa000, 0x8000, 0x8000, 0x8000, 0x0, 0x5700028, 0xc82000a140)
	/Users/craig/go-clean/src/magneto/vendor/github.com/anacrolix/torrent/storage/file_storage_piece.go:53 +0x15a
io.(*SectionReader).Read(0xc82273db60, 0xc8205aa000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/io/io.go:453 +0xd6
io.copyBuffer(0x571f2b0, 0xc8256858f0, 0x571f288, 0xc82273db60, 0xc8205aa000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/io/io.go:380 +0x247
io.Copy(0x571f2b0, 0xc8256858f0, 0x571f288, 0xc82273db60, 0xc8256858f0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.2/libexec/src/io/io.go:350 +0x64
magneto/vendor/github.com/anacrolix/torrent.(*Torrent).hashPiece(0xc820083400, 0x84, 0x0, 0x0, 0xc800000000)
	/Users/craig/go-clean/src/magneto/vendor/github.com/anacrolix/torrent/torrent.go:630 +0x2d5
magneto/vendor/github.com/anacrolix/torrent.(*Client).verifyPiece(0xc820127180, 0xc820083400, 0x84)
	/Users/craig/go-clean/src/magneto/vendor/github.com/anacrolix/torrent/client.go:1754 +0x1d7
created by magneto/vendor/github.com/anacrolix/torrent.(*Client).queuePieceCheck
	/Users/craig/go-clean/src/magneto/vendor/github.com/anacrolix/torrent/client.go:46 +0xb5
```

**Comment by anacrolix** [comment]
Thanks again. This is a race between closing the completion DB for file storage, and hashing the piece data. The solutions are to either hold the client lock while hashing pieces, or to return errors when from the file storage if it's closed. I'm not sure which I prefer.

**Comment by anacrolix** [comment]
Try with the fix. Cheers.
